### ISSUE TITLE
[g-webgl] 需要支持<canvas>元素背景透明

### ISSUE THREAD

**Issue by wkw-hlq** [antvis/g#1022]
目的：希望webglRenderer支持设置画布透明，得以能看到多个堆叠的画布，包括最底下的画布。若有办法，请留言告知我，如何设置和解决，万分感谢。

问题：我在使用"@antv/g"和'@antv/g-webgl'绘制画布时，webglRenderer 设置画布透明度无效。
补充信息：CanvasRenderer和SVGRenderer 其canvas默认透明。

[使用examples](https://g-next.antv.vision/zh/examples/shape)
代码如下：
![image](https://user-images.githubusercontent.com/23255972/170931595-11f13288-8601-4e7e-9d17-437fa9c9fe13.png)
![image](https://user-images.githubusercontent.com/23255972/170933181-e911cbb2-f595-486d-9c83-1c9dffbe24fd.png)

**Comment by xiaoiver** [comment]
关于背景色目前的实现如下：
* `g-canvas` 中通过首次渲染 `fillRect` 填充
* `g-svg` 直接设置 `<svg>` 样式属性 `background-color`

`g-webgl` 的问题应该是 clearColor 使用了不透明的白色，会尽快修复。

https://webglfundamentals.org/webgl/lessons/webgl-and-alpha.html
http://learnwebgl.brown37.net/11_advanced_rendering/alpha_blending.html

**Comment by xiaoiver** [comment]
已经在 5.1.7 版本修复。
示例：https://g-next.antv.vision/zh/examples/canvas#background
