### ISSUE TITLE
rect radius 超过宽高时，图形显示不对

### ISSUE THREAD

**Issue by zengyue** [antvis/g#1029]
复现示例： https://codesandbox.io/s/vibrant-allen-cw52k3?file=/index.js:459-465

**Comment by xiaoiver** [comment]
效果还挺诡异的。。

**Comment by zengyue** [comment]
也不能进简单处理成一半，因为左右的 radius 有可能不相等

**Comment by xiaoiver** [comment]
> 也不能进简单处理成一半，因为左右的 radius 有可能不相等

不是说设置成一半，是 `clamp` 一下：
```js
const [r1, r2, r3, r4] = radius.map((r) => clamp(r.value, 0, Math.min(w / 2, h / 2)));
```

**Comment by xiaoiver** [comment]
已在 5.1.8 版本修复，刷新链接即可
