### ISSUE TITLE
[g] Path 解析路径错误

### ISSUE THREAD

**Issue by xiaoiver** [antvis/g#1045]
L 转 C 结果有误：
https://thednp.github.io/svg-path-commander/index.html

<img width="420" alt="截屏2022-06-21 下午3 04 24" src="https://user-images.githubusercontent.com/3608471/174737223-d7da2f53-67b5-41a4-86fb-0b71bc7784cd.png">

```js
M-114.40110303700409,-36.22689089497987A120,120,0,0,1,-103.1773248562883,-61.2734823190257L-64.48582803518018,-38.29592644939107A75,75,0,0,0,-71.50068939812755,-22.641806809362418Z
```

**Comment by xiaoiver** [comment]
https://github.com/thednp/svg-path-commander/issues/17

**Comment by hustcc** [comment]
svg parse 之前是使用在 iconfont 上的文件可以 load 出来变成一个 marker，现在还有这个需求吗？

**Comment by thednp** [comment]
Issue is solved, once LGTM service comes back online to do the coeQL job, we have the SVGPathCommander v1.0.5 online and ready for you guys.
