### ISSUE TITLE
[g] 长时间运行动画导致页面崩溃

### ISSUE THREAD

**Issue by xiaoiver** [antvis/G#1125]
https://g-next.antv.vision/zh/examples/perf#path-animation

下图为执行次数无限下的动画内存使用情况：

<img width="491" alt="截屏2022-08-22 下午2 26 01" src="https://user-images.githubusercontent.com/3608471/185853255-b5c568dc-d3ec-440a-8120-67bf383944e8.png">

可以使用工具度量：https://github.com/facebookincubator/memlab

**Comment by liujingjingg** [comment]
目前内存不释放的问题有解决方案嘛
