### ISSUE TITLE
Does this framework have a supporting devtools tool?

### ISSUE THREAD

**Issue by linjunc** [antvis/G#1145]
- [ ] I have searched the [issues](https://github.com/antvis/g/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Debug  for canvas

### What does the proposed API look like?
I just want to know if there are any debugging tools available for developers to use

**Comment by xiaoiver** [comment]
我们提供了一个 Chrome 浏览器插件，帮助审查画布中的元素，以及查看元素的属性。

使用方法：https://github.com/antvis/g/tree/next/packages/g-devtool

例如下图展示了使用 G + D3 绘制的柱状图中的场景图（树状结构）：

<img width="1258" alt="截屏2022-09-05 下午2 47 23" src="https://user-images.githubusercontent.com/3608471/188382257-e5f0d06a-d8f3-4c12-a2df-1ebd608991ee.png">
