### ISSUE TITLE
G.Path 绘制面积图有问题

### ISSUE THREAD

**Issue by hustcc** [antvis/G#1172]
Path string 如下：

> M40,341.42857142857144L220.33333333333334,277.1428571428571L220.33333333333334,470L40,470ZM581,148.57142857142856L761.3333333333334,277.1428571428571L761.3333333333334,470L581,470ZM1122,20L1122,470Z

在 SVG 下显示：

![image](https://user-images.githubusercontent.com/7856674/194751848-1e893266-9694-4598-961a-05d32b59c64f.png)

在 G 中显示：

![image](https://user-images.githubusercontent.com/7856674/194751856-f2fd9fbc-559d-4f66-92ae-4de9b5afeed2.png)

带来问题：

G2 Area 绘制的时候出现异常：

![image](https://user-images.githubusercontent.com/7856674/194751888-710d898d-3715-4df1-8570-38edd3c30805.png)

**Comment by xiaoiver** [comment]
转换成三阶贝塞尔曲线后展示正常：
https://thednp.github.io/svg-path-commander/

**Comment by hustcc** [comment]
使用 [d3-shape](https://github.com/d3/d3-shape#areas) 生成的。

**Comment by xiaoiver** [comment]
转换成三阶贝塞尔曲线是正确的：

<img width="409" alt="截屏2022-10-09 下午8 44 57" src="https://user-images.githubusercontent.com/3608471/194757552-bc30e388-8194-4f46-85fb-37eb58965cfe.png">

问题出在添加 `Z` 命令的位置。
