### ISSUE TITLE
[g] 去掉 mana-syringe 以减少包体积

### ISSUE THREAD

**Issue by xiaoiver** [antvis/G#1180]
#1082

放弃了 IoC 的影响面如下：

* 需要手动处理实例化并管理依赖关系，以插件为例，原本所需的依赖可以通过构造函数注入，现在就只能通过全局 / 画布级的上下文中获取：
```js
// before
constructor(
  @inject(CanvasConfig)
  private canvasConfig: CanvasConfig,

  @inject(SceneGraphService)
  protected sceneGraphService: SceneGraphService,

  @inject(ContextService)
  private contextService: ContextService<WebGLRenderingContext>,
) {}

// after
constructor(context: CanvasContext) {}
```

* 依赖无法自动更新。IoC 容器会自动解析，例如在运行时切换渲染器时，上下文服务会随之修改。这意味着这一类依赖必须实时从上下文中获取，无法使用缓存。
* 全局容器和画布级容器通过上下文实现，每个插件的扩展点也都暂时挂在上面。

**Comment by xiaoiver** [comment]
<img width="1174" alt="截屏2022-10-18 下午6 54 56" src="https://user-images.githubusercontent.com/3608471/196411132-cfbb5979-c92b-40aa-974e-6134de4cdb35.png">

**Comment by cuidong626** [comment]
额 梭哈了
