### ISSUE TITLE
[g-svg] 优先使用用户传入的 id

### ISSUE THREAD

**Issue by xiaoiver** [antvis/G#1184]
目前生成 SVG 元素时，会将用户传入的 `name` `className` 作为 `attribute` 添加到元素上，但 `id` 使用的是内置生成的全局唯一值，用于后续拾取判定以及例如 `clipPath` 的引用：

```js
new Circle({
  id: 'my-id',
  name: 'my-name',
  style: {}
});
```

可以将内置的 `id` 放在自定义属性上例如 `data-g-id`，而用户手动传入`id` 直接输出，由用户自己保证唯一性。

```html
<g id="user-defined-id" data-id="g-circle-0">
  <circle />
</g>
```

**Comment by hustcc** [comment]
G 内部做查询的时候，使用哪个 id？

**Comment by xiaoiver** [comment]
> G 内部做查询的时候，使用哪个 id？

每个图形全局唯一的 id 是：`shape.entity`
