### ISSUE TITLE
svg模式label/text的baseline在firefox下不生效

### ISSUE THREAD

**Issue by awebird** [antvis/g#119]
### Summary
问题参考 [g6下提出的issue](https://github.com/antvis/g6/issues/642)
### Environment
Firefox 65.0.2 - windows
### Expected behavior
文字按设置的baseline呈现
### Actual behavior
baseline在firefox下不生效
### RCA
@antv\g\src\renderers\svg\painter.js l561
`el.setAttribute('alignment-baseline', BASELINE_MAP[attrs.textBaseline] || 'baseline');`
这里的alignment-baseline Firefox不支持，需要增加dominant-baseline属性，注意MAP的值也不一致，比如alignment-baseline="before-edge" 对应dominant-baseline="text-before-edge"
### 参考
[stackoverflow](https://stackoverflow.com/questions/41822995/inconsistent-svg-text-alignment-in-chrome-and-firefox)
[alignment-baseline](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/alignment-baseline)
[dominant-baseline](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/dominant-baseline)

**Comment by dengfuping** [comment]
- Closed by #141 and #165.
