### ISSUE TITLE
官网所有的用例都报错

### ISSUE THREAD

**Issue by IMSupperkaka** [antvis/G#1228]

**Comment by xiaoiver** [comment]
是在这里查看的吗？
https://g.antv.antgroup.com/examples/ecosystem/d3/#d3-barchart

不过文档里有些链接失效了，修复中。

**Comment by IMSupperkaka** [comment]
> 是在这里查看的吗？ https://g.antv.antgroup.com/examples/ecosystem/d3/#d3-barchart
> 
> 不过文档里有些链接失效了，修复中。

我是在这里看的 https://g-next.antv.vision/zh/examples/plugins/yoga/#yoga-container

**Comment by xiaoiver** [comment]
我们官网正在迁移。可以看这个：
https://g.antv.antgroup.com/examples/plugins/yoga/#yoga-container

**Comment by IMSupperkaka** [comment]
> 我们官网正在迁移。可以看这个： https://g.antv.antgroup.com/examples/plugins/yoga/#yoga-container

好的多谢
