### ISSUE TITLE
Text 缩略显示不正常

### ISSUE THREAD

**Issue by Aarebecca** [antvis/G#1233]
Demo中wordWrapWidth值置为20或120时会仅显示 `...`，为20时可以理解为长度不够，但为120时不应显示成这种形式
![image](https://user-images.githubusercontent.com/25787943/204801810-b57d5b72-e6d7-4a49-b2cc-04233e1a2a9a.png)

[Demo](https://codesandbox.io/s/unruffled-framework-e9zc5i?file=/index.js:637-650)

**Comment by xiaoiver** [comment]
没考虑到省略号宽度比截断处字符宽度还短的情况。

**Comment by xiaoiver** [comment]
已修复可验证：
https://codesandbox.io/s/solitary-waterfall-0d8zv2?file=/index.js
