### ISSUE TITLE
[g-canvas] Safari 下 sans-serif 宽度度量有误导致擦除区域偏小

### ISSUE THREAD

**Issue by xiaoiver** [antvis/G#1236]
`g-canvas` 默认开启了脏矩形渲染，会按照文本度量的区域进行擦除。

下图为 Safari 的效果，可以看出 sans-serif 度量出来的宽度有误，呈现被截断的效果：

<img width="530" alt="截屏2022-12-01 下午3 46 44" src="https://user-images.githubusercontent.com/3608471/204995883-3c8340af-475b-4384-b80e-a4d79ab484e8.png">

**Comment by hustcc** [comment]
解法怎么弄？给 measureText 的 canvas 设置样式吗？

**Comment by xiaoiver** [comment]
在 Mac 上可以用 `system-ui, -apple-system` 代替 'sans-serif'
https://fontsarena.com/blog/operating-systems-default-sans-serif-fonts/

**Comment by visiky** [comment]
> ```js
> system-ui, -apple-system, sans-serif
> ```

在我的电脑上，这个解决方案不可行 😂 chrome、 safari、firefox 都是

**Comment by Aarebecca** [comment]
感觉受影响的主要是 safari 和 node-canvas，safari 可以直接不管，node-canvas 这块测试截图和实际预览效果不一致就很难受
