### ISSUE TITLE
[Feature Request] 官网支持版本切换

### ISSUE THREAD

**Issue by songhn233** [antvis/G#1241]
- [x] I have searched the [issues](https://github.com/antvis/g/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当前官网只显示 5.0 版本，但是上层依赖（比如 G6 等）还是使用的 4.0 的 G 作为渲染器。在使用 G 定制图形时参考文档不确定升级对原有能力和暴露 API 的改动影响。

也许官网应该更明确这种版本更新，同时增加切换功能。另外在文档中看到一些关于兼容老版本 API 设计的描述，但是并没有找到迁移指南以及能力 API 上的区别。

不知道这一块有怎样的考虑呢

### What does the proposed API look like?
明确版本切换和迁移指南

**Comment by songhn233** [comment]
> 确实之前老的和新的官网都是分开部署的。 http://g.antv.vision/
> 
> 我的想法是在新官网导航栏上放一个跳转链接。

嗯，感谢回复。我觉得也可以在常见问题里明确一下版本关系？因为现在很多上层依赖还是老版本的，一开始看文档还没看出区别😂

另外API的改动和用户升级指南不知道有对应的文档或者规划吗。

**Comment by xiaoiver** [comment]
版本切换已增加：
<img width="536" alt="截屏2023-01-03 下午2 25 35" src="https://user-images.githubusercontent.com/3608471/210308888-974565b7-3340-42be-9cf2-5c4b3cbfca51.png">

升级指南之前在 yuque 上，我尽快在官网上同步一份。

**Comment by firmianaQ** [comment]
https://g.antv.vision/无法访问
