### ISSUE TITLE
Image Shape 渲染开销问题

### ISSUE THREAD

**Issue by songhn233** [antvis/G#1248]
- [x] I have searched the [issues](https://github.com/antvis/g/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在 5.0 文档中看到图片的 https://g.antv.antgroup.com/examples/perf/basic#images

API 支持 url、ImageData、和 Canvas，但是看例子似乎都是直接通过 url   image node 进行渲染

### What does the proposed API look like?
好奇不同的来源对渲染性能会不会有区别，我理解如果有现成的 ImageData 或者 Canvas 那么就可以利用类似双缓存的机制，减少渲染的链路。不知道实际情况是怎么样的

**Comment by songhn233** [comment]
写了个 ImageData 的 Demo 但是好像渲染有问题
https://codesandbox.io/s/romantic-nobel-i9sh2f?file=/index.js

**Comment by xiaoiver** [comment]
我实现了一个 demo，目前传入 ImageData 确实渲染不出来：
https://codesandbox.io/s/relaxed-knuth-e6s2z4?file=/index.js
