### ISSUE TITLE
官网，点击开始使用，404

### ISSUE THREAD

**Issue by tobemaster56** [antvis/G#1254]
https://g.antv.antgroup.com/
点击开始使用，

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/8998761/207529081-6a9286cb-a05a-486a-934f-ff6e832dc64e.png">

**Comment by tobemaster56** [comment]
报404的地址是
https://g.antv.antgroup.com/docs/guide/getting-started 
真实的地址是
https://g.antv.antgroup.com/guide/getting-started

**Comment by xiaoiver** [comment]
感谢反馈，链接地址发生了变化，马上修复。
