### ISSUE TITLE
关于依赖 G 的类库的 UMD 使用方式讨论

### ISSUE THREAD

**Issue by xiaoiver** [antvis/G#1255]
如果将 G 类比到同为视图层的 React / Vue，基于它们的类库 UMD 使用方式如下。

AntD 将 React / ReactDOM 作为 peerDependencies，因此 UMD 中是不会包含它们的，在使用时需要额外引入：

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/18.2.0/umd/react.production.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react-dom/18.2.0/umd/react-dom.production.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/antd/4.23.4/antd.min.js"></script>
```

https://github.com/ant-design/ant-design/blob/master/package.json#L292-L295
```json
"peerDependencies": {
  "react": ">=16.9.0",
  "react-dom": ">=16.9.0"
},
```

[ant-design-vue](https://github.com/vueComponent/ant-design-vue) 也同样会把 vue external 掉：
https://github.com/vueComponent/ant-design-vue/blob/main/package.json#L85-L87
```json
"peerDependencies": {
  "vue": ">=3.2.0"
},
```

使用方式如下：

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.6.11/vue.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/ant-design-vue/2.2.2/antd.min.js"></script>
```

所以一旦我们有如下类比：
* `@antv/g` 对位到 React。同样是提供图形的抽象描述，与渲染层无关。
* `@antv/g-canvas/svg/webgl` 类比 ReactDOM。实际渲染层，React 使用 DOM 我们使用 Canvas / SVG / WebGL。

是否如下使用形式才是合理的，`@antv/g` 和 `@antv/g-canvas` 也是 G2 的 peerDependencies，不应被打入 UMD 中：

```html
<script src="@antv/g.min.js"></script>
<script src="@antv/g-canvas.min.js"></script>

<script src="@antv/g2.min.js"></script>
<script src="@antv/gui.min.js"></script>
<script src="@antv/g6.min.js"></script>

<script src="@antv/g-lottie-player.min.js"></script>
<script src="@antv/g-image-exporter.min.js"></script>
```

实际上最初我设想的任何对 G 依赖的类库都应该是这种使用方式（UMD 下）：
https://github.com/antvis/G/blob/next/demo/index.html#L28-L35

### 这样做的好处

首先可以保证 UMD 下只存在一份 G 的代码，其他所有依赖避免了重复引入。

其次可以避免冲突问题，注意下面并不是 NPM 的使用方式（虽然看起来是），还是 UMD，常见于 dumi / gatsby 这样的官网生成器中。例如 canvas 来自 G2 UMD 版本中包含的 G，但 Canvas 来自独立引入的 G UMD，instanceof 判断便会返回 `false`：

```js
import { Canvas } from '@antv/g';
import { Chart } from '@antv/g2';

// 从 G2 中获取的 canvas 实例
const { canvas } = chart.context();

// 这其实是非常不合理的
canvas instanceof Canvas; // false
```

我尝试搜索了下 React 相关的问题，例如存在多个 React 实例导致的问题：
https://stackoverflow.com/questions/66488492/solve-having-more-than-one-copy-of-react-in-the-same-app

> You might have more than one copy of React in the same app See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

给出的解决方案也都是将 react / react-dom 移到 peerDependencies 中，并在打 UMD 时 external 掉：
https://stackoverflow.com/a/66497721

**Comment by xiaoiver** [comment]
### 其他考虑

从使用方便的角度讲，那肯定还是一起打在 UMD 里看上去简洁：

```html
```

**Comment by hustcc** [comment]
React 感觉不具备对比性，React 可以 external，也可以不 external，但是不能绑架开发者必须采用 external。另外，React  也做到的极高的下载量后，用户自己也会自发的去考虑 external，来保障页面的加载性能。

如果是为了 dev tool 拿到所有的图形，可以在 global 上挂载一些信息，但是不影响各自实例的使用。

**Comment by lvisei** [comment]
上层库打包两份 UMD 嘛，需要混用的情况，再提前引用 G ？

**Comment by xiaoiver** [comment]
> React 感觉不具备对比性，React 可以 external，也可以不 external，但是不能绑架开发者必须采用 external。另外，React 也做到的极高的下载量后，用户自己也会自发的去考虑 external，来保障页面的加载性能。
> 
> 如果是为了 dev tool 拿到所有的图形，可以在 global 上挂载一些信息，但是不影响各自实例的使用。

单一使用 React 的库显然是不需要 external 的我理解，正如单独使用 G2 / S2。

但如果在项目里 antd + material-react 两个同时依赖 React 的库一起用，就需要考虑 external 的问题了。不然也不会出现类似 “多个 React 实例同时使用产生冲突” 这样的问题了。
至于下载量我觉得是另一个问题，可能和用法无关（个人认为哈），external 显然是会减少加载总体积的。但也不是说 antd v1 的时候不 external，火了之后才 external 这样。或者 vue 刚出来的时候，基于 vue 的组件库就不 external。本质上还是考虑和其他同样依赖 react / vue 的库共存的问题。

而且我发现现在有一个比较尴尬的场景，就是 G 的插件 UMD 都是把 G external 的，这看起来很合理对吧，几乎所有的插件系统无论是 webpack / umi 都会这么做（可能这也是 peerDependencies 的初衷？），但插件代码里就不能出现这样的代码：

```js
import { Circle } from '@antv/g';

export function a(object) {
  if (object instanceof Circle) {}
}
```

因为在 UMD 下由于 external 会假定 `Circle` 来自 `window.G.Circle`，但如果 G2 使用了这个插件，传进来的 object 实际是通过 `window.G2.G.Circle` 实例化的，插件就无法正常工作了。

然后我也尝试去 React / Vue 代码里搜索了一下它们有没有使用类似 instanceof 这种。
