### ISSUE TITLE
[g] 连续创建 / 销毁图形存在 OOM 问题

### ISSUE THREAD

**Issue by xiaoiver** [antvis/G#1260]
连续创建大量图形后销毁内存应当回落，但实际情况是高居不下：

```js
for (let i = 0; i < circles.length; i++) {
  circles[i].destroy();
}
circles = [];
```

<img width="1251" alt="截屏2022-12-20 下午5 55 07" src="https://user-images.githubusercontent.com/3608471/208638013-e41c75fd-4bbb-4f83-94a4-193dc01b73f4.png">

lodash 中的 memoize 也存在同样问题
https://stackoverflow.com/questions/52562611/javascript-heap-out-of-memory-using-lodash-memoize

**Comment by xiaoiver** [comment]
将 Map 换成 WeakMap 后，memoized 的占用的确消失了：
<img width="889" alt="截屏2022-12-23 上午8 40 58" src="https://user-images.githubusercontent.com/3608471/209248555-53c3ee1d-f26b-441e-bf34-4e47118a8767.png">

**Comment by liujingjingg** [comment]
感觉是GPU没有释放，现在有什么解决方案嘛

**Comment by xiaoiver** [comment]
使用 Perf 工具查看了下，主要是 Canvas 销毁时（调用 `canvas.destroy()`），在 SceneGraphService 中对于图形列表的引用没有释放：

<img width="1047" alt="截屏2023-01-16 下午2 11 28" src="https://user-images.githubusercontent.com/3608471/212610046-c01155a4-bd0a-4365-bd28-7a1ac1c6e4f4.png">

**Comment by liujingjingg** [comment]
所以我现在要做的就是更新一下最新版本就可以了是嘛

**Comment by xiaoiver** [comment]
> 所以我现在要做的就是更新一下最新版本就可以了是嘛

是的，我们在 G2 的 CI 中（创建大量 Canvas 添加图形，然后销毁）验证过了，之前因为 OOM 导致 CI 挂，现在能通过了。
