### ISSUE TITLE
[g-svg] 在 Riddle 中报错

### ISSUE THREAD

**Issue by xiaoiver** [antvis/G#1264]
`g-svg` 的 UMD 版本中包含如下代码：

```js
if (parsedColor instanceof gLite.CSSRGB) {
```

但是在 Riddle 中构建出的代码如下，判断无法通过，原因是 `e` 来自：

```js
if (o instanceof e.CSSRGB) {
```

复现代码：https://riddle.alibaba-inc.com/riddles/5b680975

应当尽量避免使用 `instanceof` 判断，在 UMD 格式下会有类似问题，例如 #1255 中涉及到的关于图形、事件的判断失效。

### 解决方案

上面的例子希望判断是否为 `CSSRGB`，可以使用 `isCSSRGB()` 代替 `instanceof`，例如：

```js
function isCSSRGB(value: any) is CSSRGB {
}
```

**Comment by hustcc** [comment]
已经发包了吗？riddle 中的 demo 有验证吧？

**Comment by xiaoiver** [comment]
https://riddle.alibaba-inc.com/riddles/5b680975
发布了 5.15.9 之后 SVG 能渲染了，不会之前的报错，但事件交互无法正常使用，待排查。

**Comment by xiaoiver** [comment]
问题原因是在拾取时 `g-svg` 调用到了 `g-lite` 而非 `g` 的方法，画布中的图形列表都保存在后者中。
但 UMD 应该只存在 `g-svg` 和 `g`
Gravity 使用 System.js

<img width="834" alt="截屏2023-01-13 下午2 46 11" src="https://user-images.githubusercontent.com/3608471/212256338-101dfdae-bc2e-4baa-8ab2-616c73d5e2a7.png">

因此使用 `g-lite` 代替 `g` 就能正常工作：

```js
import { Canvas, Circle } from '@antv/g-lite';
// import { Canvas, Circle } from '@antv/g';
```

**Comment by xiaoiver** [comment]
已验证可正常渲染交互：https://riddle.alibaba-inc.com/riddles/a29a41a1

**Comment by hustcc** [comment]
G2 的 canvas + svg 渲染有验证嘛？我试了 G2 canvas 依然渲染不出来。

**Comment by xiaoiver** [comment]
> G2 的 canvas + svg 渲染有验证嘛？我试了 G2 canvas 依然渲染不出来。

g-svg + D3：https://riddle.alibaba-inc.com/riddles/2b489c15
g-canvas + D3：https://riddle.alibaba-inc.com/riddles/3a445657
g-webgl + D3：https://riddle.alibaba-inc.com/riddles/f13a6c4a

应该是 G2 还没有发新版本

**Comment by xiaoiver** [comment]
> G2 的 canvas + svg 渲染有验证嘛？我试了 G2 canvas 依然渲染不出来。

G2 报了另一个错，应该是使用了装饰器语法 Gravity 不认识，需要万木排查一下：
https://riddle.alibaba-inc.com/riddles/bc614158
