### ISSUE TITLE
canvas不停渲染 销毁 GPU累加问题

### ISSUE THREAD

**Issue by liujingjingg** [antvis/G#1279]
![image](https://user-images.githubusercontent.com/33412221/217134624-1d640528-bca2-4a4e-94e4-34d64929cff6.png)
我现在使用版本已经是最新的，但是GPU问题还是存在
![image](https://user-images.githubusercontent.com/33412221/217134708-80929542-3731-413a-bbdc-1a0cac3feaf7.png)

[https://github.com/antvis/G/issues/1265](url)

**Comment by wang1212** [comment]
建议升级到 v6 版本，v5 版本作为过渡版本，目前已经不再维护了，v6 作为主要版本会长期持续维护
