### ISSUE TITLE
transform 不生效的问题

### ISSUE THREAD

**Issue by Aarebecca** [antvis/G#1280]
[DEMO](https://codesandbox.io/s/l6dwts)

先设置 transform 后设置属性后，transform 不生效。
期望：
```ts
  rect.attr('transform', 'translate(100, 0)')
  rect.attr('x', 100);
```
等效于
```ts
  rect.attr('x', 100);
  rect.attr('transform', 'translate(100, 0)')
```

**Comment by xiaoiver** [comment]
原因是：
* `transform: 'translate(100, 0)'` 会转换成命令式调用：`translate(100, 0)`，在局部坐标系下偏移
* `x: 100` 会转换成：`setLocalPosition(100, 0)`，在局部坐标系下设置坐标

因此调用的先后顺序会有影响

**Comment by tyri1** [comment]
@xiaoiver already fixed, close this issue
