### ISSUE TITLE
d3-interpolate 未提供 CJS 产物

### ISSUE THREAD

**Issue by xiaoiver** [antvis/G#1282]
之前升级到了 3.x 版本，为了解决 snyk 问题。

`main` 指向了 ESM 版本：
https://github.com/d3/d3-interpolate/blob/main/package.json#L28
2.x 倒是提供了：https://github.com/d3/d3-interpolate/blob/df0475ae37eb410e82b6f6ea667a81dec83a71b0/package.json#L18

导致 next.js 中使用报错：
https://github.com/ant-design/ant-design-charts/issues/1802

如果不想退回到 2.x 版本，应该只能 fork 一份自己发布了。

**Comment by EvgeniyBudaev** [comment]
@xiaoiver 
Before adding to package.json: i get an error: 
[server] /home/ebudaev/Documents/web/node_modules/@antv/g-base/lib/animate/timeline.js:5
pb-web-app:dev: [server] var d3_interpolate_1 = require("d3-interpolate"); // 目前整体动画只需要数值和数组的差值计算
pb-web-app:dev: [server]                        ^
pb-web-app:dev: [server] Error [ERR_REQUIRE_ESM]: require() of ES Module /home/ebudaev/Documents/web/node_modules/d3-interpolate/src/index.js from /home/ebudaev/Documents/web/node_modules/@antv/g-base/lib/animate/timeline.js not supported.
pb-web-app:dev: [server] Instead change the require of index.js in /home/ebudaev/Documents/web/node_modules/@antv/g-base/lib/animate/timeline.js to a dynamic import() which is available in all CommonJS modules.


I added to package.json:
`  
"overrides": {
    "d3-interpolate": "2.0.1"
  }
` 

I get an error: 
 [server] /home/ebudaev/Documents/web/node_modules/@antv/path-util/lib/parse-path.js:3
pb-web-app:dev: [server] var lodash_es_1 = require("lodash-es");
pb-web-app:dev: [server]                   ^
pb-web-app:dev: [server] Error [ERR_REQUIRE_ESM]: require() of ES Module /home/ebudaev/Documents/web/node_modules/lodash-es/lodash.js from /home/ebudaev/Documents/web/node_modules/@antv/path-util/lib/parse-path.js not supported.
pb-web-app:dev: [server] Instead change the require of lodash.js in /home/ebudaev/Documents/web/node_modules/@antv/path-util/lib/parse-path.js to a dynamic import() which is available in all CommonJS modules.

Please, can you elaborate on how to fix this?

**Comment by xiaoiver** [comment]
https://github.com/vercel/next.js/issues/25454

I will try to fork `d3-color` & `d3-interpolate` and remove `type: 'module'` in their `package.json`

**Comment by xiaoiver** [comment]
But I found all the d3 packages already moved to [ESM module](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c).
https://github.com/d3/d3/issues/3469

So it seems impossible to fork all these d3 packages. I will try to find a better solution from Next.js docs.
https://nextjs.org/docs/advanced-features/compiler#module-transpilation

**Comment by EvgeniyBudaev** [comment]
@xiaoiver I have created a simple project.  https://github.com/EvgeniyBudaev/remix-ant/blob/main/app/routes/index.tsx
I get an error: 
```
Error [ERR_REQUIRE_ESM]: require() of ES Module C:\evgeniybudaev\CODE\Remix\Antv\remix-ant\node_modules\d3-interpolate\src\index.js from C:\evgeniybudaev\CODE\Remix\Antv\remix-ant\node_modules\@antv\g-base\lib\animate\timeline.js not supported.
Instead change the require of index.js in C:\evgeniybudaev\CODE\Remix\Antv\remix-ant\node_modules\@antv\g-base\lib\animate\timeline.js to a dynamic import() which is available in all CommonJS modules.
```

**Comment by JonasJonny** [comment]
@xiaoiver Victory charts "solved it" with https://www.npmjs.com/package/victory-vendor (More info at https://formidable.com/blog/2022/victory-esm/).
Then Recharts implemented it https://github.com/recharts/recharts/commit/bcb199c0d60b79fa09704413ed9a440cc0a7b1c9.
