### ISSUE TITLE
是否可提供类似G6的fitView方法

### ISSUE THREAD

**Issue by gdnwr** [antvis/G#1293]
- [ ] I have searched the [issues](https://github.com/antvis/g/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
与G6的fitView方法功能相同，让画布内容适应视口

### What does the proposed API look like?
与G6的fitView方法相同

**Comment by xiaoiver** [comment]
Mapbox 会提供类似的方法：
https://docs.mapbox.com/mapbox-gl-js/example/fitbounds/

```js
map.fitBounds([
  [32.958984, -5.353521], // southwestern corner of the bounds
  [43.50585, 5.615985] // northeastern corner of the bounds
]);
```

**Comment by xiaoiver** [comment]
在 G6 5.0 中的实现如下：
https://github.com/antvis/G6/issues/4344
