### ISSUE TITLE
@antv/react-g render不支持target为gruop

### ISSUE THREAD

**Issue by stoneox** [antvis/G#1299]
- [ ] I have searched the [issues](https://github.com/antvis/g/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
使用render向group添加circle，浏览器报错：Uncaught TypeError: Cannot read properties of undefined (reading 'createElement')
例子：https://codesandbox.io/s/antv-react-g-render-r14c3f，错误报告无法选择版本，导致无法提交issue

### What does the proposed API look like?
支持render(<CircleReact />, group)

**Comment by xiaoiver** [comment]
原因是 react reconciler 调用 `createInstance` 时，对于 Canvas 和 Group（或者其他图形），找到 document 的方式不同。
前者使用 `canvas.document`，后者应该使用 `element.ownerDocument`
