### ISSUE TITLE
G渲染线的能力增强：是否考虑将X6中的连线、路由能力，下沉到底层G中

### ISSUE THREAD

**Issue by gdnwr** [antvis/G#1336]
- [x] I have searched the [issues](https://github.com/antvis/g/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
实际需求：使用G的Yoga插件实现基于Flex布局的设备端子面板图，创建端子与设备外的光缆纤芯之前的连线，当设备或光缆移动时，中间的连线可自适应移动

### What does the proposed API look like?
希望与X6中的连线、路由相同

![微信截图_20230508093507](https://user-images.githubusercontent.com/28519600/236715256-fc8c1f9d-6e69-4781-8b73-af90dd3c11b1.png)

**Comment by xiaoiver** [comment]
感谢您的提问！Yoga 那个插件依赖 WASM，需要额外的加载时间，并且性能存在一定问题。

您是需要一个 Grid 布局么，我看 `@antv/layout` 里有这个，G6/X6 底层用的应该都是这个库。

**Comment by gdnwr** [comment]
> 感谢您的提问！Yoga 那个插件依赖 WASM，需要额外的加载时间，并且性能存在一定问题。
> 
> 您是需要一个 Grid 布局么，我看 `@antv/layout` 里有这个，G6/X6 底层用的应该都是这个库。 https://github.com/antvis/layout#readme

您好，我想要一个类似G6或X6中的边渲染能力，指定边的source、target，自动生成边，并可根据两端点的移动自动更新边。具体示例如下：
G6中：
  edges: [
    {
      source: 'node5',
      target: 'node6',
      type: 'cubic-horizontal',
    },
    {
      source: 'node5',
      target: 'node7',
      type: 'cubic-horizontal',
    },
  ]
X6中：
graph.addEdge({
  source,
  target,
  router: {},
  attrs: {},
})

**Comment by xiaoiver** [comment]
那感觉直接使用 G6 / X6 比较合适
