### ISSUE TITLE
使用 pnpm + changesets 作为 version 和 publish 方案

### ISSUE THREAD

**Issue by xiaoiver** [antvis/G#1386]
pnpm + semantic-release 在 monorepo 中使用时存在以下问题：
* 并不能自动更新依赖。例如 g-lite 依赖 g-math，当 g-math 更新时，g-lite 中的依赖版本号并没有更新。因为 semantic-release 是根据 github tag 而非 package.json 中的版本判断的：https://github.com/pmowrer/semantic-release-monorepo/issues/131
* 会提交大量的 tags

而 changesets 是 pnpm 官方推荐的 version + changelog 生成方案：
https://pnpm.io/using-changesets

因此新的发布方案如下：

1. 基于主分支（目前是 next 分支）切一个 release 分支作为开发分支
2. 每个开发者基于 release 分支切一个新分支完成他的功能，Code Review 通过以后，先合并到 release 分支
3. 整体测试完成以后，release 分支再合并到主分支，永远保证主分支的代码是足够稳定的

**Comment by pomelo-nwu** [comment]
@Aarebecca G6 和 G6VP 都可以参考下～
