### ISSUE TITLE
您好,我修改了部分代码,我怎么能够重新打包呢?

### ISSUE THREAD

**Issue by yoy-aww** [antvis/g#139]
### 如何打包g项目?

**Comment by dengfuping** [comment]
-

**Comment by dengfuping** [comment]
- `npm run build`: 打包成 `umd` 格式
- `npm run build-lib`: 打包成 `cjs` 格式
- `npm run prepublishOnly `: 打包成 `umd + cjs` 格式

具体可见 [package.json](https://github.com/antvis/g/blob/master/package.json) 中的 `scripts` 脚本命令。
