### ISSUE TITLE
addshape   为  ’arc‘ 的时候缺少fill属性

### ISSUE THREAD

**Issue by zhoustudent** [antvis/g#140]
- [ ] I have searched the [issues](https://github.com/antvis/g/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/antvis/g/blob/master/src/shapes/arc.js](https://github.com/antvis/g/blob/master/src/shapes/arc.js)

### Steps to reproduce
源码中不存在

### What is expected?
拥有这个属性

### What is actually happening?
现在还没有属性

| Environment | Info |
|---|---|
| g | 3.4.6 |
| System | 10.14.5 |
| Browser | 76.0.3809.100 |

**Comment by dengfuping** [comment]
- 圆弧 `arc` 属于 `非闭合` 图形，只有对于`闭合`图形如 `rect`、`circle`，填充属性 `fill` 才有意义。
