### ISSUE TITLE
动画的支持

### ISSUE THREAD

**Issue by dxq613** [antvis/g#16]
1. 支持 repeat 动画
2. 可以暂停、继续
3. 可以沿着某个 Path 运动

**Comment by luoyy2013** [comment]
可以沿着某个 Path 运动,这个哪里有介绍吗？

**Comment by luoyy2013** [comment]
找不到这方面的文档。我用的canvas，画了path，想做的效果是在线上有一个点，这个点沿着path运动。。

**Comment by xiaoiver** [comment]
可以尝试新版的 “路径动画”
https://g-next.antv.vision/zh/docs/api/animation#%E8%B7%AF%E5%BE%84%E5%8A%A8%E7%94%BB
