### ISSUE TITLE
[4.0] Shape 和 Group 提供获取 canvas 的方法

### ISSUE THREAD

**Issue by hustcc** [antvis/g#162]
目前 shape 和 group 提供以下方法获取 canvas 实例。

```js
shape.get('canvas');
group.get('canvas');
```

但是有个问题是，canvas 是只有在被 add 到树形结构中才能被 set 进去。如果我先构造一个子树，然后再将这个子树 add 到 canvas 中，就会导致子树中的元素 cfg.canvas 为 null。

case 及实现方式，使用 parent 数据来获取 canvas 即可，cfg 中都不用存储 canvas 这个数据：https://github.com/antvis/gui/blob/e381fa0c92fbcea7ad630aa7038c8ac208193198/src/slider/handler.ts#L168-L176

**Comment by dengfuping** [comment]
@hustcc 
- 如果先构造子树再 `add` 到 canvas 上，则只有最上层的 `group` 的 cfg.canvas 才不为空。
- 由于 canvas 在元素的渲染周期中几乎不可变，因此写入 cfg 中更合理，避免频繁向上查找 `parent` 带来的开销。
- 解决方案: `addGroup` 时将 canvas 递归写入到 children 的 cfg 中去。

**Comment by dengfuping** [comment]
- G 4.0 实际上提供了 [getCanvas](https://github.com/antvis/g/blob/4.x/packages/g-base/src/abstract/element.ts#L86) 方法，只不过默认实现为
```js
getCanvas(): ICanvas {
  return this.get('canvas');
}
```

**Comment by hustcc** [comment]
1. 关于遍历 children 添加 canvas 的问题

给个简单的示例：

```js
class Handler extends Group {
  initial() {
    this.add(new Rect());
  }
}

class Slider extends Groups {
  initial() {
    this.add(new Handler());
  }
}

// test case

const canvas = new Canvas();

const slider = new Slider();

// 那么我在做下面这一步的时候
// 我需要将 slider 中的 handler 设置 canvas 实例、并且将 handler 中 rect 设置 canvas 实例。
canvas.add(slider);
```

如果这样做的话，我用某一个 g 的 ui 组件的时候，我都需要去感知他的内部结构。

2. parent vs canvas

两者其实 parent 的信息更完全，考虑的只是性能问题而增加属性，完全可以通过缓存的方法结构来处理，达到的性能是一样的。g 本身的代码也不需要去管理 canvas 这个属性。

**Comment by dengfuping** [comment]
> 关于遍历 children 添加 canvas 的问题

- 是指 `G` 内部把这个逻辑做掉，上层不需要关心

**Comment by hustcc** [comment]
这里可能还是要讨论下， 递归的 setCanvas 和 getCanvas 向上查找+缓存的方式，哪一个更优。个人认为 setCanvas 递归整个树形，性能并不如 getCanvas 向上查找。

 - getCanvas： lg(n)
 - setCanvas： o(n)

**Comment by dengfuping** [comment]
- 目前来看，性能上 `getCanvas 向上查找+缓存` 是要好一点，两者的本质区别是:
    - `getCanvas`: 添加 element 不会调用 getCanvas，只有手动调用了 getCanvas 才会执行查找过程(可将 canvas 缓存到 element 上，避免重复执行)，渲染周期内并不是每个 element 都执行。
        - 优点: 性能稍好
        - 缺点: 不兼容，上层需要将 `cfg.canvas` 和 `get('canvas')` 的写法都改用 `getCanvas()` 的方式
    - `setCanvas`: 添加 element 必定会调用 setCanvas，并且渲染周期内每个 element 都会执行一次。
        - 优点: 性能稍差
        - 缺点: 兼容性好，上层不需要改动，即可支持 gui 的需求。
- 看改动的性价比吧，自己更倾向于 `setCanvas` 的兼容性方案。

**Comment by dxq613** [comment]
这个问题不用纠结，在add 上处理就好了，原因在于调用 add(element） 的概率非常低，大部分情况都是直接 addGroup ，不会有子元素。只有 clone 一个 group 或者把一个 group 从一个 canvas 移动到另一个时才会触发，所以在添加 时级联设置子元素的 canvas 更合适。而且 get('canvas') 的频率远远大于  set('canvas')
