### ISSUE TITLE
i hope g-canvas can able to zoom in and out

### ISSUE THREAD

**Issue by hcxcomeon** [antvis/G#1659]
- [ ] I have searched the [issues](https://github.com/antvis/g/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I hope the canvas can be zoomed in and out when using the annotation plugin, Because annotation requires more precise operations sometimes, then I can zoom in the canvas to annotation the box

### What does the proposed API look like?
like 'setZoomByViewportPoint'，The coordinates of points change with the canvas zooms in and out

**Comment by xiaoiver** [comment]
Thanks for your feature request. Can you use camera API like setZoom?

Here's the DEMO.
https://codesandbox.io/p/sandbox/shi-yong-g-hui-zhi-path-forked-t6nvl7?file=%2Findex.js%3A50%2C23

**Comment by wang1212** [comment]
You can use camera api like `setZoom(zoom: number)` / `setZoomByViewportPoint(zoom: number, viewportPoint: vec2)`.
