### ISSUE TITLE
设置 renderer 为 svg， lineAppendWidth 失效

### ISSUE THREAD

**Issue by baizn** [antvis/g#167]
### Summary
如题，复现Demo请参考：https://codepen.io/viewweiwu/pen/YzKEZPe?editors=0010。

**Comment by dengfuping** [comment]
- `svg` 版本目前不支持 `lineAppendWidth` 属性，因为 `svg` 的拾取走的是浏览器的默认行为,这算是 `svg` 与 `canvas` 版本的一个 `gap`。

**Comment by viewweiwu** [comment]
好的，我觉得是不是在语雀文档里提醒一下会比较好。
我有个想法就是在这个 shape 之上画一条透明的线，通过这条透明的来做交互，只不过有点绕，不知道这样做是否会有隐患...
https://codepen.io/viewweiwu/pen/ZEzaZWG?editors=0010

**Comment by dengfuping** [comment]
- 效果上是可以的，也算一种实现方案。不过在事件处理上可能会有问题，如果能将透明的线代理到 `实际的那条线` 应该就可以了。
