### ISSUE TITLE
如何在本地跑起来？

### ISSUE THREAD

**Issue by sunscheung** [antvis/g#17]
### git clone到本地后执行以下步骤
$ git clone git@github.com:antvis/g.git
$ npm install
$ npm run dev

想在本地跑起来，运行demo可以么？
方便的话给出简要步骤

**Comment by dxq613** [comment]
目前的 demo 貌似是前一个版本的，可以运行一下test ，tnpm run test-live

**Comment by sunscheung** [comment]
执行   npm run test-live  可以跑起来
