### ISSUE TITLE
Path不能显示

### ISSUE THREAD

**Issue by yyyt2020** [antvis/G#1703]
注：https://antv-issue-helper.surge.sh 链接不能选择版本号，导致不能提交问题。

相关仓库：G

重现问题步骤：
第一步：打开https://g.antv.antgroup.com/zh/examples/shape/path/#l-command
第二步：点击代码上方的stackblitz
第三步：在stackblitz中调试代码看不到Path的显示

预览
![QQ截图20240530165147](https://github.com/antvis/G/assets/5064606/96dd3c32-d2f5-451d-97e3-1187b7ca598a)

**Comment by yyyt2020** [comment]
试着path无效，改为d是可以的，代码如下：
const line = new Path({
  style: {
    d: 'M 100 100 L 200 200',
    stroke: '#F04864',
    lineDash: [10],
  },
});

**Comment by xiaoiver** [comment]
感谢反馈，文档还没有更新
