### ISSUE TITLE
G 能否开放参数, 来自定义双击的判定时机, 目前是写死的 200 ms

### ISSUE THREAD

**Issue by lijinke666** [antvis/G#1710]
### 版本

```ts
"@antv/g": "^6.0.6",
"@antv/g-canvas": "^2.0.7",
"@antv/g-lite": "^2.0.5"
```

### 问题

![image](https://github.com/antvis/G/assets/21015895/6aeea880-9952-4146-94c5-3c5609e2b9f9)

看源码是写死的 200 ms (不知道有没有找对地方), 希望能开放参数来自定义, 原生的 dbclick 大概是 500ms 左右

https://github.com/antvis/G/blob/277abff24936ef6f7c43407a16c5bc9260992511/packages/g-lite/src/services/EventService.ts#L316-L323

### 期望

增加一个 `dbclickTimeStamp` 类似的 API, 可以通过 `Canvas` 透传

```ts
import { Canvas } from '@antv/g';

new Canvas({
  dbclickTimeStamp: 500
})
```

```

**Comment by hustcc** [comment]
不太确定为啥不用原生 dbclick 去实现！如果改的话，可以这样的 API 更好一些。

```ts
import { runtime }  from '@antv/g'; 
runtime.dbClickDeley = 500;
```

**Comment by Zhaohanqi12** [comment]
> 不太确定为啥不用原生 dbclick 去实现！如果改的话，可以这样的 API 更好一些。
> 
> ```ts
> import { runtime }  from '@antv/g'; 
> runtime.dbClickDeley = 500;
> ```

请明确该如何修改间隔时间，是贵司处理还是我这边修改api？

**Comment by lijinke666** [comment]
> > 不太确定为啥不用原生 dbclick 去实现！如果改的话，可以这样的 API 更好一些。
> > ```ts
> > import { runtime }  from '@antv/g'; 
> > runtime.dbClickDeley = 500;
> > ```
> 
> 请明确该如何修改间隔时间，是贵司处理还是我这边修改api？

他说的应该是预想的 API, 这个需要 G 这边额外开发, 开放 API, 而不是谁修改的问题 @hustcc 啥时候安排?

**Comment by lijinke666** [comment]
> > > 不太确定为啥不用原生 dbclick 去实现！如果改的话，可以这样的 API 更好一些。
> > > ```ts
> > > import { runtime }  from '@antv/g'; 
> > > runtime.dbClickDeley = 500;
> > > ```
> > 
> > 
> > 请明确该如何修改间隔时间，是贵司处理还是我这边修改api？
> 

@Zhaohanqi12 hustcc 说的应该是预想的 API, 这个需要 G 这边额外开发, 开放 API, 而不是谁修改的问题 @hustcc 啥时候安排?

**Comment by lijinke666** [comment]
```ts
const s2Options = {
  transformCanvasConfig() {
    return {
      dblClickSpeed: 500
    }
  }
}
```

**Comment by Zhaohanqi12** [comment]
请问会在哪个版本生效？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jinke ***@***.***&gt;; 
发送时间: 2024年7月19日(星期五) 下午5:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [antvis/G] G 能否开放参数, 来自定义双击的判定时机, 目前是写死的 200 ms (Issue #1710)














 const s2Options = {   transformCanvasConfig() {     return {       dblClickSpeed: 500     }   } }

**Comment by lijinke666** [comment]
下周发布, 关注下 changelog, 发布后应该是 2.0.0-next.26

**Comment by Zhaohanqi12** [comment]
谢谢！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jinke ***@***.***&gt;; 
发送时间: 2024年7月19日(星期五) 晚上6:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [antvis/G] G 能否开放参数, 来自定义双击的判定时机, 目前是写死的 200 ms (Issue #1710)














 
下周发布, 关注下 changelog, 发布后应该是 2.0.0-next.26
