### ISSUE TITLE
调用 setLocalScale api 对 Path 进行缩放，效果不对

### ISSUE THREAD

**Issue by yvonneyx** [antvis/G#1741]
对 Path 路径调用 API setLocalScale 进行缩放，效果不对。

```
const line = new Line({
  style: {
    x1: 200,
    y1: 100,
    x2: 400,
    y2: 100,
    stroke: '#1890FF',
    lineWidth: 2,
    cursor: 'pointer',
    transformOrigin: 'center,
  },
});
line.setLocaleScale(1, 2);
```

Line 默认

![image](https://github.com/user-attachments/assets/07ffa7a0-d259-4920-81f0-4fa0dff7c3f6)

y轴方向拉伸一倍 ✅

![image](https://github.com/user-attachments/assets/7fbab993-7dc9-4231-a347-9ae572fe13ac)

Path 默认

<img width="994" alt="image" src="https://github.com/user-attachments/assets/b2b5c9f1-5c84-489f-ba9a-ec47ee36114d">

y轴方向拉伸一倍 ❌ 斜率、位置都发生了变化

<img width="1059" alt="image" src="https://github.com/user-attachments/assets/a8b282bb-93f4-47fa-bee9-e4a3580036a5">

**Comment by wang1212** [comment]
可以查看以下示例，Path 与 Line 的缩放效果一致：

> https://stackblitz.com/edit/vitejs-vite-cpp6ce?file=src%2Fcase-g.ts

---

几何变换会影响图形的绘制坐标，对于斜率处于 0 ～ 1 之间的 Line 来说，除非 x/y 两个方向的缩放系数一致，否则斜率将发生变化。

_对于你提供的示例中的水平线，是因为设置了 `transformOrigin: 'center'`，这就意味着对于 Line 这个图形 y 方向上的所有坐标相对于缩放中心的 **dy=0**，即 `dy*scale=0`，因此线的位置未发生变化。_

而且，默认情况下随着缩放，线的绘制宽度也会成比例缩放，也可以让线宽不随缩放变化：https://www.stefanjudis.com/today-i-learned/how-to-disable-scaling-for-stroke-width/
