### ISSUE TITLE
[g-webgl] 在元素拾取时 Y轴的触发坐标 时反的 在canvas 渲染模式时是元素拾取没问题的

### ISSUE THREAD

**Issue by aopend** [antvis/G#1747]
[g-webgl] 在元素拾取时 Y轴的触发坐标 时放的 在canvas 渲染模式时是元素拾取没问题的，
导致无法正确的选中 图形元素 

https://github.com/user-attachments/assets/33d539fc-4f80-47ec-b1aa-ac1a78f8019f

**Comment by lolilukia** [comment]
canvas 渲染模式如何开启？

**Comment by wang1212** [comment]
> canvas 渲染模式如何开启？

see https://g.antv.antgroup.com/api/renderer/canvas
