### ISSUE TITLE
官网案例demo报错

### ISSUE THREAD

**Issue by the-lemonboy** [antvis/G#1748]
官网好多案例demo报错。
![image](https://github.com/user-attachments/assets/423429fc-d836-42cc-aeb7-ba9dc3923c5e)

**Comment by gdnwr** [comment]
是呀，好多demo都报错了。有些插件vite也用不了，如g-plugin-yoga

**Comment by wang1212** [comment]
#1709 

这些示例报错的问题会在后续修复，可能会比较久，其中一些问题短期内可能没有太多时间去处理

**Comment by 8502596** [comment]
https://github.com/antvis/G2/issues/6512

**Comment by wang1212** [comment]
可以看看目前新发布的官网实例已经正常。

https://g.antv.antgroup.com/zh/examples/canvas/container#shared-container
