### ISSUE TITLE
DisplayObject 的 anchor被移除了吗，ts报style没有该属性，也无法设置，官方demo无效

### ISSUE THREAD

**Issue by yyds-18** [antvis/G#1775]
DisplayObject 的 anchor被移除了吗，ts报style没有该属性，也无法设置，官方demo无效

    "@antv/g": "^6.0.13",
    "@antv/g-canvas": "^2.0.12",
    "@antv/g-components": "^2.0.9"

另：  https://antv-issue-helper.surge.sh  g的version opts 获取异常

**Comment by Aarebecca** [comment]
是的，在 https://github.com/antvis/G/pull/1627 中已经移除该属性

**Comment by yyds-18** [comment]
> 是的，在 #1627 中已经移除该属性

thanks
