### ISSUE TITLE
npm 包中缺少 source，但是 sourcemap 的路径包含 src

### ISSUE THREAD

**Issue by wangtao0101** [antvis/G#1781]
RT

**Comment by wang1212** [comment]
首先，感觉你的反馈。

--- 

sourcemap 文件中可以包含 `sourcesContent` 字段来替代源代码文件（虽然这不是规范的一部分，但这是现在大多数库的默认行为），可以查看以下资料进一步了解。

- https://github.com/tc39/source-map/issues/42
- https://web.dev/articles/source-maps

--- 

另外，我已经用一个 vite 项目来进行尝试，发现 G 的 sourcemap 在 Chrome Devtools 中确实没有生效，将会跟进解决。
