### ISSUE TITLE
🐛 Paths with `markerEndOffset` are drawn incorrectly

### ISSUE THREAD

**Issue by yvonneyx** [antvis/G#1809]
`markerStartOffset` 效果符合预期，但 `markerEndOffset` 还不对~

<img width="413" alt="Google Chrome 2024-10-29 11 42 25" src="https://github.com/user-attachments/assets/44c96bce-429c-4963-b619-758703ea70ab">

<img width="410" alt="Google Chrome 2024-10-29 11 42 35" src="https://github.com/user-attachments/assets/933e5c0e-33f9-46b6-bf9b-f526761f82a5">

**Comment by yvonneyx** [comment]
```ts
import { Canvas, Path } from "@antv/g";
import { Renderer as CanvasRenderer } from "@antv/g-canvas";

const canvasRenderer = new CanvasRenderer();

const canvas = new Canvas({
container: "container",
width: 600,
height: 500,
renderer: canvasRenderer,
});

const arrowMarker = new Path({
style: {
d: "M 10,10 L -10,0 L 10,-10 Z",
stroke: "#1890FF",
transformOrigin: "center",
},
});

const path = new Path({
style: {
lineWidth: 1,
stroke: "#54BECC",
d: "M 0,40 L 100,100",
markerStart: arrowMarker,
markerStartOffset: 30,
markerEnd: arrowMarker,
markerEndOffset: 30,
},
});

canvas.appendChild(path);
```

**Comment by wang1212** [comment]
> ```ts
> import { Canvas, Path } from "@antv/g";
> import { Renderer as CanvasRenderer } from "@antv/g-canvas";
> 
> const canvasRenderer = new CanvasRenderer();
> 
> const canvas = new Canvas({
> container: "container",
> width: 600,
> height: 500,
> renderer: canvasRenderer,
> });
> 
> const arrowMarker = new Path({
> style: {
> d: "M 10,10 L -10,0 L 10,-10 Z",
> stroke: "#1890FF",
> transformOrigin: "center",
> },
> });
> 
> const path = new Path({
> style: {
> lineWidth: 1,
> stroke: "#54BECC",
> d: "M 0,40 L 100,100",
> markerStart: arrowMarker,
> markerStartOffset: 30,
> markerEnd: arrowMarker,
> markerEndOffset: 30,
> },
> });
> 
> canvas.appendChild(path);
> ```

`L` 命令没有问题，是 `Q`/`C`/`A` 这几个命令绘制逻辑有点问题
