### ISSUE TITLE
antv/g6@v5  使用了 image 节点时，@antv/g-plugin-image-loader 在 g6 画布销毁后，并没有任何地方 IMAGE_CACHE.clear 释放 内存，多次切换页面后，内存一直增加

### ISSUE THREAD

**Issue by mini2s** [antvis/G#1813]
![27bc5f240add26a0ef8ede990b5c4827](https://github.com/user-attachments/assets/25d286cd-c0f6-4d60-b731-eea7a1ce2134)

**Comment by wang1212** [comment]
`@antv/g-plugin-image-loader` 版本是多少

**Comment by mini2s** [comment]
> `@antv/g-plugin-image-loader` 版本是多少

最新版
![image](https://github.com/user-attachments/assets/fcbac4e6-dfc8-4e10-8606-b1a16c6801a7)

**Comment by wang1212** [comment]
已经定位到原因，下个版本修复掉

**Comment by mini2s** [comment]
> 已经定位到原因，下个版本修复掉

感谢

**Comment by wang1212** [comment]
已在最新版本中修复 #1816

**Comment by mini2s** [comment]
> 已在最新版本中修复 #1816

看了一下 https://github.com/antvis/G/pull/1816 的 commit 信息，没有看到 ts 或 js 的变更，全是json和md 文件变更，是不是漏掉代码了？我更新最新版后还是存在 内存泄漏问题 😂
![image](https://github.com/user-attachments/assets/d6f36295-5c20-4298-a5fb-1f487ff86704)

**Comment by wang1212** [comment]
> > 已在最新版本中修复 #1816
> 
> 看了一下 #1816 的 commit 信息，没有看到 ts 或 js 的变更，全是json和md 文件变更，是不是漏掉代码了？我更新最新版后还是存在 内存泄漏问题 😂 ![image](https://private-user-images.githubusercontent.com/143020328/382771168-d6f36295-5c20-4298-a5fb-1f487ff86704.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3Mjg2MDksIm5iZiI6MTczMDcyODMwOSwicGF0aCI6Ii8xNDMwMjAzMjgvMzgyNzcxMTY4LWQ2ZjM2Mjk1LTVjMjAtNDI5OC1hNWZiLTFmNDg3ZmY4NjcwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQxMzUxNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTM0MzNhYWZlYjNmOTRmNTliNDU3YjBmOTcwMzVkYWI3MzkyZmVjMmM5MWE4MzBlNzc3MDIxODZmZDgyZWZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oNgIr_ez5xLg1q9OPJYulrCRmbLExkxwi9lg6yNqw58)

相关代码在这里：https://github.com/antvis/G/blob/a3e07c1/packages/g-plugin-image-loader/src/ImagePool.ts#L35

---

如果还存在内存泄露问题请确认以下几点：

- 更新下所有 g 相关的包，不要只单独更新 `g-plugin-image-loader`
- 可以在项目的 node_modules 中找到该包，打印一下 `IMAGE_CACHE` 变量的日志，查看 G6 canvas 销毁后资源是否被释放
- 确认第二步的结果，判断是否是 Image 元素导致的内存泄露，进一步反馈更多细节

**Comment by mini2s** [comment]
> * 更新下所有 g 相关

好的我全部重新下载试试

**Comment by mini2s** [comment]
> > > 已在最新版本中修复 #1816
> > 
> > 
> > 看了一下 #1816 的 commit 信息，没有看到 ts 或 js 的变更，全是json和md 文件变更，是不是漏掉代码了？我更新最新版后还是存在 内存泄漏问题 😂 ![image](https://private-user-images.githubusercontent.com/143020328/382771168-d6f36295-5c20-4298-a5fb-1f487ff86704.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3Mjg2MDksIm5iZiI6MTczMDcyODMwOSwicGF0aCI6Ii8xNDMwMjAzMjgvMzgyNzcxMTY4LWQ2ZjM2Mjk1LTVjMjAtNDI5OC1hNWZiLTFmNDg3ZmY4NjcwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQxMzUxNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTM0MzNhYWZlYjNmOTRmNTliNDU3YjBmOTcwMzVkYWI3MzkyZmVjMmM5MWE4MzBlNzc3MDIxODZmZDgyZWZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oNgIr_ez5xLg1q9OPJYulrCRmbLExkxwi9lg6yNqw58)
> 
> 相关代码在这里：https://github.com/antvis/G/blob/a3e07c1/packages/g-plugin-image-loader/src/ImagePool.ts#L35
> 
> 如果还存在内存泄露问题请确认以下几点：
> 
> * 更新下所有 g 相关的包，不要只单独更新 `g-plugin-image-loader`
> * 可以在项目的 node_modules 中找到该包，打印一下 `IMAGE_CACHE` 变量的日志，查看 G6 canvas 销毁后资源是否被释放
> * 确认第二步的结果，判断是否是 Image 元素导致的内存泄露，进一步反馈更多细节

![image](https://github.com/user-attachments/assets/61afa1cf-63a1-4c0a-a90a-d93ad0b5f22e)

多次重复切换页面，最终切换到空白页面后 内存会回落一些，但是整体趋势仍然一直增加

**Comment by wang1212** [comment]
> > > > 已在最新版本中修复 #1816
> > > 
> > > 
> > > 看了一下 #1816 的 commit 信息，没有看到 ts 或 js 的变更，全是json和md 文件变更，是不是漏掉代码了？我更新最新版后还是存在 内存泄漏问题 😂 ![image](https://private-user-images.githubusercontent.com/143020328/382771168-d6f36295-5c20-4298-a5fb-1f487ff86704.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3Mjg2MDksIm5iZiI6MTczMDcyODMwOSwicGF0aCI6Ii8xNDMwMjAzMjgvMzgyNzcxMTY4LWQ2ZjM2Mjk1LTVjMjAtNDI5OC1hNWZiLTFmNDg3ZmY4NjcwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNFQxMzUxNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTM0MzNhYWZlYjNmOTRmNTliNDU3YjBmOTcwMzVkYWI3MzkyZmVjMmM5MWE4MzBlNzc3MDIxODZmZDgyZWZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oNgIr_ez5xLg1q9OPJYulrCRmbLExkxwi9lg6yNqw58)
> > 
> > 
> > 相关代码在这里：[`a3e07c1`/packages/g-plugin-image-loader/src/ImagePool.ts#L35](https://github.com/antvis/G/blob/a3e07c1/packages/g-plugin-image-loader/src/ImagePool.ts#L35)
> > 如果还存在内存泄露问题请确认以下几点：
> > 
> > * 更新下所有 g 相关的包，不要只单独更新 `g-plugin-image-loader`
> > * 可以在项目的 node_modules 中找到该包，打印一下 `IMAGE_CACHE` 变量的日志，查看 G6 canvas 销毁后资源是否被释放
> > * 确认第二步的结果，判断是否是 Image 元素导致的内存泄露，进一步反馈更多细节
> 
> ![image](https://private-user-images.githubusercontent.com/143020328/382988158-61afa1cf-63a1-4c0a-a90a-d93ad0b5f22e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3NzU0OTcsIm5iZiI6MTczMDc3NTE5NywicGF0aCI6Ii8xNDMwMjAzMjgvMzgyOTg4MTU4LTYxYWZhMWNmLTYzYTEtNGMwYS1hOTBhLWQ5M2FkMGI1ZjIyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQwMjUzMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NjBiZmY3NDFhYzI0YTAwNzBjYjFiZDQzZGZhYzFlYzAxMTg2OTRiZjI4ZjdjNjUwMmQwNWYxNDcyZTM5OTU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EbIVNrZgQ8B0fLYaCnj-LjoJ3hF8OzaVrBwQTx9RQSk)
> 
> 多次重复切换页面，最终切换到空白页面后 内存会回落一些，但是整体趋势仍然一直增加

找到原因了，G6 使用的 APIs 在销毁实例时没有触发 G 元素的 destroy 事件，导致资源未被释放，后续会在 G6 或 G 中修复

**Comment by wang1212** [comment]
https://github.com/antvis/G6/pull/6478

**Comment by wang1212** [comment]
G 新版本 #1819 已经修复，等待 G6 发版即可

**Comment by mini2s** [comment]
> G 新版本 #1819 已经修复，G6 [antvis/G6#6481](https://github.com/antvis/G6/pull/6481)

发现一个新问题

```javascript
  releaseRef(ref: CounterValue) {
    this.#cacheStore.keys().forEach((key) => {
      this.release(key, ref);
    });
  }
```

```this.#cacheStore.keys().forEach ``` 这个函数调用发现有些版本浏览器会报错

出现问题的浏览器如下：
Edge 版本: 109.0.1518.115  
chrome: 116.0.5845.141 
firefox: 115.1.0esr

没有出现问题的版本如下：
Edge 版本: 130+  
chrome: 130+ 
firefox:  132+

1.打开浏览器控制台
2. 输出 ```new Map().keys().forEach```
3.发现出问题的浏览器 返回的 forEach 都是 undefined

**Comment by wang1212** [comment]
> > G 新版本 #1819 已经修复，G6 [antvis/G6#6481](https://github.com/antvis/G6/pull/6481)
> 
> 发现一个新问题
> 
> ```js
>   releaseRef(ref: CounterValue) {
>     this.#cacheStore.keys().forEach((key) => {
>       this.release(key, ref);
>     });
>   }
> ```
> 
> `this.#cacheStore.keys().forEach ` 这个函数调用发现有些版本浏览器会报错
> 
> 出现问题的浏览器如下： Edge 版本: 109.0.1518.115 chrome: 116.0.5845.141 firefox: 115.1.0esr
> 
> 没有出现问题的版本如下： Edge 版本: 130+ chrome: 130+ firefox: 132+
> 
> 1.打开浏览器控制台 2. 输出 `new Map().keys().forEach` 3.发现出问题的浏览器 返回的 forEach 都是 undefined

这个似乎是新的语法目前支持的有限：https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator/forEach

这周五之前发布版本时会解决掉这个问题
