### ISSUE TITLE
支持 css 缩放

### ISSUE THREAD

**Issue by dxq613** [antvis/g#183]
G2 中有大量关于外层 css 进行了缩放的 issue，需要在 G  层次支持一下：
https://github.com/antvis/g2/issues/912

**Comment by dengfuping** [comment]
- Reproducible demo: https://codesandbox.io/s/g-container-css-transform-e4tg6

**Comment by maplor** [comment]
> * `scale`、`rotate` 和 `skew` 都有这个问题，应该将 `container` 的 CSS transform 转换为内部的 `matrix` 计算。参考重现 demo: https://codesandbox.io/s/g-container-css-transform-e4tg6

很多情况是 `container` 外层dom有css scale，只考虑 `container` 的 CSS transform 无法解决问题。

**Comment by fancyboynet** [comment]
请问缩放的问题解决了吗？

**Comment by w91** [comment]
我发现之前有个解决缩放问题的pr合并之后又被回滚了，这个是出于什么原因，后面大概什么时候能解决这个缩放的问题

**Comment by PathFun** [comment]
解决了吗

**Comment by dengfuping** [comment]
- 已支持 CSS 缩放，不过目前需要手动开启:
```js
const canvas = new Canvas({
   supportCSSTransform: true,
})
```

**Comment by PathFun** [comment]
谢谢哦





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "诸岳"<notifications@github.com&gt;; 
发送时间: 2020年12月3日(星期四) 上午10:58
收件人: "antvis/g"<g@noreply.github.com&gt;; 
抄送: "吻得太逼真"<360603837@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [antvis/g] 支持 css 缩放 (#183)





  
已支持 CSS 缩放，不过目前需要手动开启:
  const canvas = new Canvas({    supportCSSTransform: true, })
