### ISSUE TITLE
Path style lineDash 支持超过2位的数组

### ISSUE THREAD

**Issue by HuangLiangchen** [antvis/G#1866]
- [ ] I have searched the [issues](https://github.com/antvis/g/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
path画出的线条无法实现点划线

### What does the proposed API look like?
const path = new Path({ style: { lineDash: [20, 10, 1, 10] } });

**Comment by hustcc** [comment]
四个值分别代表什么？

**Comment by HuangLiangchen** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/API/CanvasRenderingContext2D/getLineDash
参考文档,lineDash接受多位数组,表示每一段实线,虚线的长度
<img width="1390" alt="image" src="https://github.com/user-attachments/assets/c1ab2983-6bf6-474c-af82-6b5838a1d012">

**Comment by hustcc** [comment]
看起来应该容易实现，有兴趣来 pr 嘛～

**Comment by HuangLiangchen** [comment]
ok
