### ISSUE TITLE
The 'mouseleave' event cannot be triggered on the canvas

### ISSUE THREAD

**Issue by toxicant123** [antvis/G#1875]
## Steps To Reproduce

source code:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script
            src="https://unpkg.com/@antv/g/dist/index.umd.min.js"
            type="application/javascript"
    ></script>
    <!-- G 渲染器，支持 Canvas2D/SVG/WebGL -->
    <script
            src="https://unpkg.com/@antv/g-canvas/dist/index.umd.min.js"
            type="application/javascript"
    ></script>
</head>
<body>
    <div id="container"></div>
    <script>
        // 从核心包中引入画布、Circle 等对象
        const {Canvas} = window.G;

        // 创建一个渲染器，这里使用 Canvas2D
        const canvasRenderer = new window.G.Canvas2D.Renderer();

        // 创建画布
        const canvas = new Canvas({
            container: 'container',
            width: 600,
            height: 500,
            renderer: canvasRenderer,
        });

        canvas.addEventListener('mouseleave', () => {
            console.log('mouseleave')
        })

        canvas.addEventListener('mouseout', () => {
            console.log('mouseout')
        })
    </script>
</body>
</html>
```

## The current behavior

When the mouse is moved out of the canvas element, only the "mouseout" event can be triggered, the "mouseleave" event cannot be triggered.

## The expected behavior

The "mouseleave" event will be triggered.

**Comment by wang1212** [comment]
According to the DOM specification, the `mouseleave` event does not bubble. If you add an element instance and listen to the event of the element instance, it can be triggered normally.

> https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseleave_event

```ts
canvas.addEventListener(CanvasEvent.READY, () => {
  console.log('ready');

  const rect = new Rect({
    style: {
      x: 200,
      y: 100,
      width: 300,
      height: 200,
      fill: '#1890FF',
      stroke: '#F04864',
      lineWidth: 4,
      radius: 8,
    },
  });
  canvas.appendChild(rect);

  rect.addEventListener('mouseleave', () => {
    // This will be triggered successfully
    console.log('mouseleave');
  });
});
```

**Comment by toxicant123** [comment]
Can you explain it in more detail?

![image](https://github.com/user-attachments/assets/52c38d0f-e8e7-4c1b-8e0c-8caec2228d4c)

Assume that the canvas and rect in the above picture are bound to mouseleave events. If the mouse moves according to the red arrow, shouldn't the mouseleave events of canvas and rect be triggered at the same time?

**Comment by wang1212** [comment]
> Can you explain it in more detail?你能更详细地解释一下吗？
> 
> ![image](https://private-user-images.githubusercontent.com/82657149/398787381-52c38d0f-e8e7-4c1b-8e0c-8caec2228d4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyNjQ2OTUsIm5iZiI6MTczNTI2NDM5NSwicGF0aCI6Ii84MjY1NzE0OS8zOTg3ODczODEtNTJjMzhkMGYtZThlNy00YzFiLThlMGMtOGNhZWMyMjI4ZDRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDAxNTMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5MDllZTRjZDJiZDgwZjc4ZmY4YjE4N2ExY2VkZDlkY2Q5ZDZmNjNmMGE5MTNhMzhiZDYxZmU0NGM4NTViMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Y_9LloSG0XUarTU4rv-kBYQVAyU28oIwbt_zPgkOH4o)
> 
> Assume that the canvas and rect in the above picture are bound to mouseleave events. If the mouse moves according to the red arrow, shouldn't the mouseleave events of canvas and rect be triggered at the same time?假设上图中的canvas和rect绑定了mouseleave事件。如果鼠标按照红色箭头移动，那么canvas和rect的mouseleave事件不是应该同时触发吗？

Let me explain this problem. First of all, the meaning of `canvas` here is not clear enough. It may mean two things.

1. `canvas` represents the DOM container for drawing elements

```ts
import { Canvas } from '@antv/g';

const canvas = new Canvas();

canvas.addEventListener('mouseleave', () => {
    console.log('mouseleave');
});
```

You might have written code similar to the above. If you want to listen to events on the canvas container, you can adjust the code to look like this:

```ts
canvas.getContextService().getDomElement().addEventListener('mouseleave', () => {
    console.log('mouseleave');
});
```

Why can't we just listen to G's canvas instance to achieve this? This is because the design focus of the rendering engine is the element instance in the canvas container, and the canvas container is a virtual concept.

2. `canvas` is just a normal G element like `rect`

The reason why the event of the canvas element is not triggered is that during the event processing, only the top-level element is considered when picking elements (if there are overlapping elements). This is a unified design of most rendering engines. Considering business scenarios and performance optimization, usually only the event logic of the top-level element needs to be processed.

**Comment by toxicant123** [comment]
Thank you for your patience in explaining.
