### ISSUE TITLE
[4.0] shape.getBBox() 当 shape.attr('path') 中包含 NaN 时，默认应该返回 0，而不是 NaN

### ISSUE THREAD

**Issue by simaQ** [antvis/g#210]
The issue which is not created via https://antv-issue-helper.surge.sh will be closed immediately.

---

注意：不是用 https://antv-issue-helper.surge.sh 创建的 issue 会被立即关闭。

如图：
![image](https://user-images.githubusercontent.com/6628666/66888098-df1e6e80-f00f-11e9-9e5b-e55b05c264d2.png)

![image](https://user-images.githubusercontent.com/6628666/66888110-e5144f80-f00f-11e9-861f-7d387dc7a5a9.png)

默认应该处理为 0 方便上层使用者

**Comment by dengfuping** [comment]
- G 3.x 计算包围盒时，会忽略 `path` 属性中的 `NaN`，而不是当做 0 处理。参考: https://codesandbox.io/s/g-canvas-linedash-emqnz
- 因此 4.x 的 [修复方案](https://github.com/antvis/g/pull/211) 与 3.x  保持一致，

**Comment by dengfuping** [comment]
- Closed by #211.
