### ISSUE TITLE
[4.0] 局部刷新 BUG

### ISSUE THREAD

**Issue by simaQ** [antvis/g#222]
path 图形的局部刷新导致绘制出错。

复现代码：http://riddle.alibaba-inc.com/riddles/2ec0411a

开启局部刷新，path 就绘制不完整，如下图
![image](https://user-images.githubusercontent.com/6628666/67215741-9d008d00-f454-11e9-99b1-fbab46504cea.png)

关闭局部刷新时，绘制正常：
![image](https://user-images.githubusercontent.com/6628666/67215845-c4eff080-f454-11e9-835c-2e4b7d4689c4.png)
****

**Comment by dengfuping** [comment]
- Closed by [g-canvas@0.1.0-beta.5](https://github.com/antvis/g/releases/tag/%40antv%2Fg-canvas%400.1.0-beta.5)
