### ISSUE TITLE
clip 支持设置的样式属性

### ISSUE THREAD

**Issue by baizn** [antvis/g#225]
- [ ] I have searched the [issues](https://github.com/antvis/g/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
设置了裁剪后，支持设置裁剪的样式，如stroke、lineWidth等

### What does the proposed API look like?
支持设置裁剪的样式属性

**Comment by dengfuping** [comment]
- 试了一下，Canvas 和 SVG 的 `clip` 都不支持设置 `fill`、`stroke` 和 `strokeWidth` 等属性，就算设置了实际表现也是无效。

**Comment by dengfuping** [comment]
- 和 @dxq613 讨论确定，`clip` 应该只涉及形状，不支持设置样式属性，应该使用具体的 shape 完成。

**Comment by xiaoiver** [comment]
对于 clipPath，仅有几何属性会影响
