### ISSUE TITLE
[4.0] G path 动画有问题

### ISSUE THREAD

**Issue by simaQ** [antvis/g#232]
可复现 demo: http://riddle.alibaba-inc.com/riddles/a3af2097

**Comment by dengfuping** [comment]
- 原因定位: 由于带有拐角的 `path` 包围盒计算不准确，使得在局部刷新模式下，重绘时清除的 `region` 不足够大，导致没有完全 clear 之前的绘制。
- 解决方案: 带拐角 `path` 的包围盒准确计算方案，考虑到性能，只会计算最外层的四个顶点。

**Comment by dengfuping** [comment]
- Closed by [@antv/g-canvas@0.1.0-beta.8](https://github.com/antvis/g/releases/tag/%40antv%2Fg-canvas%400.1.0-beta.8)
