### ISSUE TITLE
G 4.0  marker 的更新动画问题

### ISSUE THREAD

**Issue by simaQ** [antvis/g#236]
描述：marker 的更新动画不符合预期
![2019-10-28 14-46-50 2019-10-28 14_47_25](https://user-images.githubusercontent.com/6628666/67657562-15ee7000-f992-11e9-8414-b09f3870d5c7.gif)

可复现代码：http://riddle.alibaba-inc.com/riddles/a3af2097

预期结果：可参考 G 3.X 的更新动画：http://riddle.alibaba-inc.com/riddles/71818436

![2019-10-28 14-48-07 2019-10-28 14_48_45](https://user-images.githubusercontent.com/6628666/67657567-1b4bba80-f992-11e9-86d8-dff8ac252ecb.gif)

**Comment by dengfuping** [comment]
- g-svg 的 marker 动画也有问题，单独开一个 issue 和 PR 解决。

**Comment by dengfuping** [comment]
- Closed by [@antv/g-canvas@0.1.0-beta.8](https://github.com/antvis/g/releases/tag/%40antv%2Fg-canvas%400.1.0-beta.8)
