### ISSUE TITLE
[4.0] path 的 bbox 计算问题

### ISSUE THREAD

**Issue by simaQ** [antvis/g#252]
问题描述：对于较规则的 path，比如矩形，bbox d的计算误差太大。

复现 riddle: https://riddle.alibaba-inc.com/riddles/b9895ed4

**Comment by dengfuping** [comment]
- `path` 的包围盒计算采取更为准确的算法，除了计算出夹角处的实际线宽以外，还考虑了其在水平和垂直方向上的投影长度。

**Comment by dengfuping** [comment]
- Closed by [@antv/g-canvas@0.1.0-beta.10](https://github.com/antvis/g/releases/tag/%40antv%2Fg-canvas%400.1.0-beta.10).
