### ISSUE TITLE
text shape多行文本高度计算错误

### ISSUE THREAD

**Issue by EarlyH** [antvis/g#253]
- [x] I have searched the [issues](https://github.com/antvis/g/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://jsfiddle.net/tsm4hfar/1/](https://jsfiddle.net/tsm4hfar/1/)

### Steps to reproduce
当出现多行文本(text)，且非第一行最宽时，通过measureText方法获取的宽度不正确(仅为第一行宽度)。

### What is expected?
通过measureText方法获取的宽度正确

### What is actually happening?
通过measureText方法实际只返回了第一行宽度

| Environment | Info |
|---|---|
| g | 3.4.6 |
| System | Mac OS 10.14.1 |
| Browser | Chrome 78.0.3904.70 |

**Comment by xiaoiver** [comment]
新版提供了 `getLineBoundingRects` 用于获取多行文本的包围盒： 
https://g-next.antv.vision/zh/docs/api/basic/text#getlineboundingrects-rectangle
