### ISSUE TITLE
[4.0] path 无法绘制

### ISSUE THREAD

**Issue by simaQ** [antvis/g#254]
复现 riddle: https://riddle.alibaba-inc.com/riddles/2634f537

**Comment by dengfuping** [comment]
- 和 #252 是同一个问题，`path` 的包围盒计算存在问题。

**Comment by simaQ** [comment]
这个问题解决了吗？我的版本是 11，仍然无法绘制.... 

https://riddle.alibaba-inc.com/riddles/2634f537

**Comment by dengfuping** [comment]
- 应该在 #256 这个 PR 中修复了，但后来可能被覆盖掉了，我重新看下。

**Comment by simaQ** [comment]
> * 应该在 #256 这个 PR 中修复了，但后来可能被覆盖掉了，我重新看下。

恩，好的呢

**Comment by dengfuping** [comment]
- 问题已修复:
![image](https://user-images.githubusercontent.com/14918822/69231265-c0d60080-0bc3-11ea-8d11-ad0a67320870.png)

**Comment by dengfuping** [comment]
- Closed by [@antv/g-canvas@0.1.0-beta.12](https://github.com/antvis/g/releases/tag/%40antv%2Fg-canvas%400.1.0-beta.12)
