### ISSUE TITLE
[4.0] marker symbols 的命名统一问题

### ISSUE THREAD

**Issue by simaQ** [antvis/g#257]
https://github.com/antvis/g/blob/4.x/packages/g-canvas/src/shape/marker.ts#L29

是否可以统一采用驼峰命名？

'triangleDown'

**Comment by dengfuping** [comment]
- 通常是暴露给用户的 API (接口或属性) 是小驼峰格式，如果值类型的话一般会采取分隔符的格式，比如常用的中划线 `triangle-down`。这么改的初衷是什么呢？

**Comment by simaQ** [comment]
除了枚举值、常量等采用大写，其他大部分都是采用驼峰写法的吧，初衷是为了保持统一~  G2 是全部采用驼峰的

https://github.com/antvis/g2/blob/master/src/geom/shape/point.js#L17

**Comment by simaQ** [comment]
这个最后的结论是啥？

**Comment by dengfuping** [comment]
- 我理解 `marker symbols` 也是枚举类型，只不过在 `G` 这层同时也将其作为了函数名。主要是统一成小驼峰形式，会有兼容性的问题。或者两者形式都支持，文档中只给出 `小驼峰` 的枚举值？萧叔 @dxq613 的意见呢？

**Comment by dengfuping** [comment]
- 结论: G 这边和 G2 保持一致，均使用小驼峰，G 这边会做下兼容，支持两者写法，但文档中只透出小驼峰形式。

**Comment by simaQ** [comment]
更新下，G2 内部最后讨论，对于常量的命名，均使用小写字母 + '-' 连接符的方式~~~
