### ISSUE TITLE
[4.0]局部刷新问题

### ISSUE THREAD

**Issue by simaQ** [antvis/g#273]
用 G 复现没有成功，但是在 G2 里面是有问题的，我在创建 Canvas https://github.com/antvis/g2/blob/b772007788b8cba10986154a709f763f17f2f8e9/src/chart/chart.ts#L38 的时候将局部刷新关闭 `localRefresh: false // 局部刷新`  柱状图的更新就没有问题。

![2019-11-27 15-28-12 2019-11-27 15_28_47](https://user-images.githubusercontent.com/6628666/69702661-ab645780-112a-11ea-83dc-8a86d18c9840.gif)

开启的话就会有问题。现象如下：

![121212](https://user-images.githubusercontent.com/6628666/69702667-ae5f4800-112a-11ea-9f6c-53deb7ddc171.gif)

demo 地址：https://github.com/antvis/g2/blob/74030d585cea93cbca44958d46fb6913d56528de/examples/gallery/basic/demo/interval.js

运行调试方式：

1. clone g2 项目，
2. npm install
3. 运行 npm start
4. 进入http://localhost:8000/zh/examples/gallery/basic#interval 这个链接，即可调试

**Comment by dengfuping** [comment]
- @simaQ 应该是 `Geometry` 的 [销毁重建逻辑](https://github.com/antvis/g2/blob/74030d585c/src/geometry/base.ts#L651) 有问题，`newData` 如果和 `data` 有相同 [id](https://github.com/antvis/g2/blob/74030d585c/src/geometry/base.ts#L939) 的数据，就会有这样的问题。
- 比如以下数据，月份作为 `xField`，其值被当做 Geometry 元素 id，新老数据如果都有这条记录，更新时就不会销毁。
```js
const data = [
  { name: 'London', 月份: 'Jan.', 月均降雨量: 18.9 },
  { name: 'London', 月份: 'Feb.', 月均降雨量: 8.8 },
];
const newData = [
  { name: 'London', 月份: 'Jan.', 月均降雨量: 5 },
];
```

**Comment by simaQ** [comment]
Geometry 的逻辑是这样的，data 中的两条数据对应两个 Shape，我会根据策略对数据打  ID，如果数据发生更新了，我会根据这个 ID 去判断这条数据对应的 Shape 是应该做**更新**还是做**销毁**逻辑，在这个例子下， Jan. 数据应该做更新操作，Feb. 数据对应的 shape 需要被销毁，这个逻辑是没有错的。

你可以尝试将更新动画关闭: `chart.interval().position('月份*月均降雨量').animate({ update: false });` 绘制是 OK 的，但是更新动画开启就有问题

**Comment by simaQ** [comment]
刚刚试了下，要是把初始的入场动画关闭或者是使用矩阵变换，就是正常的，很奇怪。我明天直接去找你好了~~~

**Comment by dengfuping** [comment]
@simaQ 好的，根据这个思路我再排查下
