### ISSUE TITLE
关于 WebGL 版本的一些思考

### ISSUE THREAD

**Issue by xiaoiver** [antvis/g#281]
# 目标

为 G2、G6 提供基础 WebGL 渲染能力，和已有版本（Canvas 2D、SVG）保持统一接口不变。同时为 未来的上层 3D 图表方案提供渲染能力。

目前 uber 也在这个方向进行了一些尝试：https://graph.gl/gatsby/

WebGL 版本带来的优势：
* 海量点渲染（graph.gl 目标 10,000+ nodes）
* 高性能拾取
* GPU 进行复杂布局计算

# 方案

和 L7 之前的渲染场景一样，不需要一个完整的 WebGL 引擎，而是一个 WebGL Library。后者仅是针对 WebGL API 的简单抽象，类似 `jquery` 之于 DOM API。

因此目前 L7 选择了 `regl`。WebGL API 之所以难用，主要在于状态管理，`regl` 将其抽象成`资源`和`命令`，同时提供了优秀的缓存。值得一提的是社区有很多 `regl` 同类思路的实现，例如 https://github.com/doodlewind/beam
实现思路：https://zhuanlan.zhihu.com/p/93500639

内部需要实现以下功能，未来 L7 也可以直接使用：
* Shader 模块化管理。
* 拾取。WebGL 通用的 Color-based Picking
* SceneGraph。实现 `Group`
* GPGPU 能力。用于布局计算

但 WebGL 版本也存在一些问题，例如渲染的文字无法选中。

# 构建方案调整

由于 WebGL 版需要引入 Shader 代码，类似：
```typescript
import commonVertex from './shaders/common.vert.glsl';
```

`tsc` 显然无法处理 `glsl`：
https://stackoverflow.com/questions/48741570/how-can-i-import-glsl-as-string-in-typescript
并且需要考虑到后续针对 Shader 代码的压缩优化方案，这一点在 L7 中应用如下：
https://github.com/antvis/L7/blob/master/dev-docs/%E6%9E%84%E5%BB%BA%E6%96%B9%E6%A1%88.md#%E5%86%85%E8%81%94-webgl-%E5%B8%B8%E9%87%8F

因此需要借助其他构建工具以文本形式引入 GLSL 文件，目前常用的方式有：
* `babel` 插件
* 使用 `Webpack/Rollup` 相关 `loader`

L7 受限于 Webpack4 暂时不支持多种 target（web + webworker）混合的输出模式，和 Mapbox 一样选择了 Rollup，因此使用了 `babel` 插件的[方式](https://github.com/antvis/L7/blob/master/dev-docs/%E6%9E%84%E5%BB%BA%E6%96%B9%E6%A1%88.md#cdn)，`tsc` 仅负责输出 declaration files。G 则可以直接使用 Webpack Loaders。

# 测试方案

同 L7，使用 `headless-gl` 进行渲染结果的像素比对：
https://github.com/antvis/L7/blob/master/dev-docs/%E8%87%AA%E5%8A%A8%E5%8C%96%E6%B5%8B%E8%AF%95%E6%96%B9%E6%A1%88.md

**Comment by dxq613** [comment]
产品的定位主要有三个方向：
1. webgl 的 2D 图形，提升性能的考虑
2. 小数据量 10000 一下的 3D 图形支持，主要应用于 G2、G6 支持 3D 图表
3. 超大规模数据的支持 L7 地理可视化方向

现在看起来第二个方向更合适一些，canvas、group 和 shape 层的接口统一，在 G2、G6中仅需要增加新的 shape 即可。
同 L7 的整合更多是一些技术解决方案的统一。

**Comment by vellengs** [comment]
@xiaoiver 一直关注这个，但看样子有段时间没什么进展了，没计划了么？
