### ISSUE TITLE
请教几个问题

### ISSUE THREAD

**Issue by liaozeen** [antvis/G#289]
1. 怎么给 canvas 设置矩阵，将矩阵应用到所有元素的矩阵变换中？使用场景是移动和缩放画布。
2. 怎么在 canvas 上设置绘图属性，应用到所有图形上？使用场景是我希望缩放画布的同时改变 lineWidth 的值，使所有图形的线宽在缩放过程中不会随之放大缩小

**Comment by dengfuping** [comment]
- 目前还不支持在 canvas 上设置全局属性，包括矩阵和绘图样式。
- 这两个场景目前还没有遇到过，有相关的使用场景吗，或者哪个可视化库或者系统应用了这些场景呢？

**Comment by liaozeen** [comment]
像画图工具一样，可以缩放整个画布大小，画布里的所有图形也随之缩放

**Comment by dengfuping** [comment]
- 画布缩放的时候，图形也会自动缩放吧。

**Comment by liaozeen** [comment]
所以就希望可以设置画布 canvas 的矩阵属性，来实现对画布的整体缩放和移动

**Comment by dengfuping** [comment]
@baizn G6 中的缩放、平移等整体操作是怎么做的呢，应该不是针对画布的吧。

**Comment by northWink** [comment]
大佬您好，我目前的一个场景跟您第二问题的场景一致，就是希望线条的宽度保持定量，不会随着鼠标放大缩小，我目前没有思路，所以想请教您一下，第二个问题您有方案了吗，
