### ISSUE TITLE
如何直接传入canvas dom而不是container

### ISSUE THREAD

**Issue by Mamba-working** [antvis/g#290]
- [ ] I have searched the [issues](https://github.com/antvis/g/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
使用react-map-gl的时候会直接提供canvasOverlay，如果使用HTMLOverlay 来new Canvas那么宽高还需要自己指定
希望可以直接传入一个canvasDOM来创建实例

### What does the proposed API look like?
``` javascript
const canvas = new Canvas({
 canvasDOM: document.querySelector('#map-canvas')
})
```

**Comment by dengfuping** [comment]
- 可以关注下 #195，支持传入特定画布的 `context`，能够满足你的需求。

**Comment by xiaoiver** [comment]
新版可以直接传入 HTMLCanvasElement 或者 OffscreenCanvas
https://g-next.antv.vision/zh/docs/api/canvas#canvas
