### ISSUE TITLE
如何提供更易用的 GPU 渲染和计算能力？

### ISSUE THREAD

**Issue by xiaoiver** [antvis/g#291]
# 问题背景

ref #281 

WebGL 版本的 G 想做什么：
* 为 G2、G6、L7 提供底层高性能图形渲染、交互能力。
* GPGPU 提供复杂布局算法的计算能力。目前已有一些不错的实现：
  * 力导布局实现1 https://github.com/jaredmcqueen/analytics
  * 实现2 https://nblintao.github.io/ParaGraphL/
* 3D 图表，已有的一些优秀实现（部分也用到了 GPGPU 能力）
  * echarts.gl
  * SplatterJS 针对散点图进行的优化「Splatterplots: Overcoming Overdraw in Scatter Plots」[🔗](http://graphics.cs.wisc.edu/Papers/2013/MG13/)
  * [FluidDiagrams](https://projects.isds.tugraz.at/fluiddiagrams/)「FluidDiagrams: Web-Based Information Visualisation using JavaScript and WebGL」[🔗](http://diglib.eg.org/bitstream/handle/10.2312/eurovisshort.20141155.043-047/043-047.pdf?sequence=1&isAllowed=y)
* 提供探索、理解以及展示数据的新方式：
  * instance-based visualizations，不同布局下灵活切换。例如微软的 [Sanddance](https://sanddancehome.azurewebsites.net/?p=3309)：

![1575511631124-1b158a86-ff33-4632-a52f-d4873526c452](https://user-images.githubusercontent.com/3608471/70215540-a893e300-1778-11ea-921b-f65d1d36167c.gif)
![1575511567058-8d0758d2-0fb5-454e-a217-b7be8563b1ea](https://user-images.githubusercontent.com/3608471/70215541-a92c7980-1778-11ea-9c69-17fe29f7b8cb.gif)

关于第一点，上层调用 G 的 API 基本不变。着重想探讨下第二和第四点，即用户如何更简单地使用 G 提供的 GPU 渲染和计算能力。更直接的，如何简单地写 Shader 代码，即使完全不了解 GLSL 语法。

常见的 WebGL 引擎/库（Three.js、Mapbox、Deck.gl）提供的扩展方式（自定义 ShaderMaterial、自定义图层）都要求用户具备 WebGL 基础知识，学习 GLSL 语言完成 Shader 代码的编写，这个门槛是很高的，即使对于 G 的上层用户 G2、G6 来说也是一样。例如 G6 想在 GPU 中完成力导布局的计算，也得学习 GLSL 才能完成移植，G2-Plot 想实现类似 sanddance 效果同理。
那有没有普通 JS 开发者能够快速上手的方案呢？

# 如何帮助 JS 开发者简单地写 Shader

最近看到 EuroVis 2017 上的一篇论文：「Stardust: Accessible and Transparent GPU Support
for Information Visualization Rendering」[🔗](https://stardustjs.github.io/publications/eurovis2017-stardust.pdf)
其中介绍了 [Stardust](https://stardustjs.github.io/)：
* 支持 WebGL 和 WebVR。用户不需要学习平台相关的底层基础知识。
* 针对 D3 使用者，数据绑定 API 设计成 D3 风格
* 用户使用自定义的 Mark 编程语言（TS 子集）写 Shader，针对 JS 开发者完全屏蔽了 GLSL 细节，更容易上手。
* 不同于 d3-scale，用户使用 Mark 语言自定义的 Scale 会被编译到 Shader 代码里，最终在 GPU 中执行，这是高性能动画的关键。[示例](https://stardustjs.github.io/documentation/data-binding#stardust-scales)

自定义的 Mark 语言相比 GLSL，对于 JS 开发者友好太多了。下面是一个在 Shader 中定义组合图形的代码：
```typescript
// Import predefined marks
import { Circle, Line } from P2D;
// Define a utility mark
mark VLine(x: float, y: float) {
    Line(Vector2(x, y - 3), Vector2(x, y + 3), 1);
}
mark RangeBarWithCircle(
  x: float, y: float,
  xmin: float, xmax: float
) {
  // Emit the VLine mark defined above
  VLine(xmin, y);
  VLine(xmax, y);
  // Emit predefined marks, Line and Circle
  Line(Vector2(xmin, y), Vector2(xmax, y), 1);
  Circle(Vector2(x, y), 2);
}
```

当然内置图形（circle、rect、polyline）也都是用这种语法定义的：
https://github.com/stardustjs/stardust/blob/dev/packages/stardust-core/src/mark/marks/marks.ts

而在 instance-based visualizations 场景下，Sanddance 效果通过 Mark 语法写也并不复杂，这意味着如果 G2-Plot 想实现类似效果也不需要写 GLSL 了。在 Shader 中改变每个 instance 的位置保证了三种布局切换时的流畅。
https://stardustjs.github.io/examples/sanddance/

![sandance](https://user-images.githubusercontent.com/3608471/70215399-5c48a300-1778-11ea-89ca-62cb463e6f69.gif)

下面介绍下 Mark 这个自定义语言是如何编译成 GLSL 的。

## DSL -> GLSL 的编译流程

下图的整个编译流程十分巧妙，且充分考虑到了生成 Shader 的性能：

<img width="1009" alt="屏幕快照 2019-12-05 下午2 03 52" src="https://user-images.githubusercontent.com/3608471/70215222-01af4700-1778-11ea-9bca-9d52d7f85db3.png">

* （1、3 步）由于需要支持 WebGL、WebVR 目标平台，自定义语言首先经过编译器前端编译成平台无关的中间代码。
* （2、6、7 步）根据用户对数据绑定相关 API 的调用情况，判断出各个属性应该生成**顶点数据 attribute 还是 uniform**。例如这里 y 是常量 100，显然应该作为 uniform 传入，而 x 应该最终以顶点数组传入。这一步可以显著减少不必要的顶点数组内存占用，其实 L7 之前也有设想，但还没有实现。另外这种方式需要给每个顶点编号（第 6 步 emitIndex，每个三角形三个顶点），在最终生成的代码中就会生成三个分支，每个三角形的每个顶点进入各自分支投影后得到最终位置。
* （4、5 步）编译器后端完成中间代码到目标平台代码的生成。对于 WebGL 平台需要生成 Vertex/Fragment Shader。这里也能看出 DSL 相比 GLSL 对于开发者友好太多了。
* （8 步）将编译好的 Shader 和数据交给目标平台 renderer 渲染。

当然这个方案也有很大的改进空间，尤其是在工程化方面：
* 目前编译是在运行时完成，完全可以利用 `babel plugin` / `webpack loader` 在**构建时**完成。
* 用户代码通过字符串传入，开发体验并不好。完全可以在开发时直接写 `.mark`  文件，配合编辑器插件还能实现语法高亮。类似 L7 现在写 GLSL，利用 vs-code GLSL 插件一样。

**Comment by dxq613** [comment]
DSL -> GLSL 的转换应该还做不到完全兼容吧？

**Comment by xiaoiver** [comment]
> DSL -> GLSL 的转换应该还做不到完全兼容吧？

DSL 只是中间代码，到目标平台的转换靠编译器后端完成，例如针对 WebGL 就生成 GLSL。因此一定无法覆盖某一个语言的全部特性。但只需要具备特定场景下需要的描述能力就足够了：

因此论文里也介绍了 starbust 目前的一些应用场景，都可以用 DSL 描述：
1. instance-based visualizations。用 DSL 描述每个 instanced 的位置，在 Shader 中完成平滑的布局切换：
![ins](https://user-images.githubusercontent.com/3608471/70234533-ccb4eb80-179b-11ea-8e55-b102e893cefc.gif)
2. Isotype Visualization。支持导入 SVG 转换成 DSL 定义的 Mark：
![ins3](https://user-images.githubusercontent.com/3608471/70234613-fe2db700-179b-11ea-9083-baa6474c2966.gif)
3. Glyph-based Visualization。记得步茗分享过？
![ins4](https://user-images.githubusercontent.com/3608471/70235275-98dac580-179d-11ea-9c4c-2c905ef1adcf.gif)
4. 同一套中间代码，通过编译器后端生成不同平台代码（WebGL、OpenGL、WebVR），以适应不同展示环境：
<img width="1010" alt="屏幕快照 2019-12-05 下午8 28 07" src="https://user-images.githubusercontent.com/3608471/70235392-d5a6bc80-179d-11ea-89c1-ffc2f7d03e99.png">

**Comment by xiaoiver** [comment]
当然 stardust 也存在一些限制（论文末尾也提到了）或者说后续可以完善的点：
1. Fragment Shader 特性支持不足
2. 不支持 SceneGraph。这意味着 Group 相关功能缺失，只能单个 instance 进行动画
