### ISSUE TITLE
[4.0] localRefresh 开启图形绘制不出来

### ISSUE THREAD

**Issue by hustcc** [antvis/g#292]
在 `chart.ts` 关闭 localeRefresh 就好了。如下图：

![image](https://user-images.githubusercontent.com/7856674/70218668-5eadfb80-177e-11ea-872f-3fefe2408cdb.png)

复现方式:

```bash
git clone git@github.com:antvis/G2.git

git checkout 4.x

tnpm start
```
然后打开 `url xxx /zh/examples/column/stack#wind-rose`.

**Comment by dengfuping** [comment]
- 和 #287 这个问题一样，将在  #297 中解决。

**Comment by dengfuping** [comment]
- Closed by #297.
