### ISSUE TITLE
Supply missing method for G 4.0

### ISSUE THREAD

**Issue by dengfuping** [antvis/g#295]
- Path
    - [x] [getTotalLength()](https://github.com/antvis/g/blob/3.x-stable/src/shapes/path.js#L154)
    - [x] [getPoint(ratio)](https://github.com/antvis/g/blob/3.x-stable/src/shapes/path.js#L214)
    - [x] getStartTangent() (注: SVG 版本暂不支持)
    - [x] getEndTangent()  (注: SVG 版本暂不支持)
- Line
    - [x] getTotalLength
    - [x] [getPoint(ratio)](https://github.com/antvis/g/blob/3.x-stable/src/shapes/line.js#L70)
- Polyline
    - [x] getTotalLength
    - [x] [getPoint(ratio)](https://github.com/antvis/g/blob/3.x-stable/src/shapes/polyline.js#L167)
    - [x] getStartTangent()
    - [x] getEndTangent()
- Group
    - [x] getChildByIndex(index)
    - [x] contain(element)
    - [x] removeChild(element, destroy=true)

**Comment by baizn** [comment]
后面缺少的我补充到这里：
- getStartTangent
- getEndTangent

**Comment by baizn** [comment]
GraphEvent 中缺少 canvasX 和 canvasY 属性，表示 Canvas 坐标，用户时候时不需要在单独计算。

**Comment by dengfuping** [comment]
> GraphEvent 中缺少 canvasX 和 canvasY 属性，表示 Canvas 坐标，用户时候时不需要在单独计算。

- 修改画布导致的坐标变换，目前 G 这一层没有做处理。G6 原先是自行处理的，可以讨论下是否在 G 4.0 中支持。@dxq613

**Comment by dengfuping** [comment]
- @baizn 缺失方法已全部提供，更新到最新版 `@antv/g-canvas@0.3.3` 即可。
