### ISSUE TITLE
给 Group 增加 findByClassName 方法

### ISSUE THREAD

**Issue by Yanyan-Wang** [antvis/g#301]
- [ ] I have searched the [issues](https://github.com/antvis/g/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在 addShape 时 attrs 中有一个 string 类型的属性 className。可以通过 group.findByClassName('classnamexxx') 找到对应的 shape。

### What does the proposed API look like?

API
```javascript
/**
 * 在该组中查找 shape
 * @param {string} classname 根据 classname 查找，与 addShape 时写在 attrs 中的 className 对应。
 * @return {Shape[]} 返回所有 className 为 classname 的 Shape 列表
 */
findByClassName(classname);
```

-----------------
USAGE
```javascript
group.addShape('text', {
  attrs: {
    //...
      className: 'group-text'
  }
})
//....
let textShape = group.findByClassName('group-text')[0];
//...
```

**Comment by dengfuping** [comment]
- 根据 `元素名称` 进行查找比较常用，因此 `Group` 只新增 `findByName` 方法:
```js
/**
 * 根据 name 查找元素列表
 * @param {string}      name 元素名称
 * @return {IElement[]} 元素
 */
findByName(name: string): IElement[];
```

- 其他查找方式可以通过传入自定义的 filter 函数实现， 比如 `group.find(filterFn)` 或者 `group.findAll(filterFn)`

**Comment by hustcc** [comment]
感觉不如直接提供 querySelector 啊😂

**Comment by dengfuping** [comment]
> 感觉不如直接提供 querySelector 啊😂
- `querySelector` 要考虑的情况就比较多了，那样就会实现的比较重。基本上 `findXXX` 方法就够用了。
