### ISSUE TITLE
使用 instanced array 批量绘制同类图形，减少 draw call

### ISSUE THREAD

**Issue by xiaoiver** [antvis/g#314]
# 问题背景

根据目前 G 的 API 风格，每次调用 `addShape()` 便会创建一个对应的 `Model`，对应一条 draw call。
可以看到仅仅绘制 1000 个 `Circle`，FPS 就只有 25 左右了。

<img width="1035" alt="屏幕快照 2019-12-12 下午7 42 36" src="https://user-images.githubusercontent.com/3608471/70709318-96391c80-1d17-11ea-8c1c-61912ceb58ea.png">

# 改进思路

L7 中的 `Layer` 可以看作是一组同类图形的绘制集合，批量绘制的好处是减少 draw call 至一条，仅需要把各个对象的属性传入顶点数组中。另外可以使用 `instanced array` 进一步减少顶点数组大小，在 `Circle` 这个例子中，四个顶点可以共用位置、颜色等实例属性。

但 G 的场景有两点和 L7 不同，主要来自于每个图形的独立性：
1. G 需要考虑每个图形的动画，尤其是位置的改变需要将 `modelMatrix` 传入顶点数组。由于 `attribute` 不支持 `mat4` 数据类型，需要将 4x4 矩阵分解成 4 个 `vec4` 传入。
可以参考 https://medium.com/@pailhead011/instancing-with-three-js-part-2-3be34ae83c57
2. L7 中一个图层中每个图形有很多共有的属性（例如 `opacity`），可以通过 `uniform` 传入，而 G 中每个属性都需要使用 `attribute`

为了避免每次 `addShape()` 调用都频繁改变顶点数组 `ArrayBuffer` 的长度，参考 Mapbox 做法。每次扩展数组时，都给予一定的富余量（系数决定），这样的好处就是后续只需要通过 `subData()` 改变局部数据而避免了 `ArrayBuffer` 的内存重新分配：
```typescript
/**
 * Implementation of the StructArray layout:
 * [0]: Int16[2]
 *
 * @private
 */
emplaceBack(v0: number, v1: number) {
  const i = this.length;
  // 首先改变数组长度
  this.resize(i + 1);
  // 末尾追加数据
  return this.emplace(i, v0, v1);
}

emplace(i: number, v0: number, v1: number) {
  const o2 = i * 2;
  this.int16[o2 + 0] = v0;
  this.int16[o2 + 1] = v1;
  return i;
}

resize(n: number) {
  this.reserve(n);
  this.length = n;
}

reserve(n: number) {
  if (n > this.capacity) {
    this.capacity = Math.max(n, Math.floor(this.capacity * RESIZE_MULTIPLIER), DEFAULT_CAPACITY);
    // 重新分配内存
    this.arrayBuffer = new ArrayBuffer(this.capacity * this.bytesPerElement);

    const oldUint8Array = this.uint8;
    this._refreshViews();
    if (oldUint8Array) this.uint8.set(oldUint8Array);
  }
}
```

⚠️需要使用 dynamic hint 告知 driver 顶点数组是会发生变化的：https://community.khronos.org/t/stream-draw-vs-dynamic-draw/41651

**Comment by dengfuping** [comment]
- G 目前是把 mat3 的数据分解为一个 vec9，主要是考虑一维数组比较好处理，动画插值时也方便。
