### ISSUE TITLE
[4.0] getBBox没有考虑设置的Clip

### ISSUE THREAD

**Issue by zqlu** [antvis/g#316]
![image](https://user-images.githubusercontent.com/1142242/70767159-1c4a7700-1d9b-11ea-8ac8-23ebd34a8dde.png)

**Comment by dengfuping** [comment]
- 包围盒计算如果要考虑 `clip`，复杂度会提升，主要有以下几种情况需要判断:
    - 当 `clip` 的包围盒大于 shape 的包围盒时，应该取 shape 的包围盒；
    - 当 `clip` 的包围盒小于 shape 的包围盒时，应该取 clip 的包围盒；
    - 当 `clip` 的包围盒与 shape 的包围盒相交时，应该取两者的交集；
    - 当 `clip` 的包围盒与 shape 的包围盒不相交时，包围盒长、宽均为 0；
- 如果不考虑 `clip`，不会影响当前的拾取；如果考虑 `clip`，则包围盒计算会更加准确，但会带来额外的开销，且没有明显的收益。因此现阶段包围盒计算暂不考虑 `clip` @zqlu 。

**Comment by zqlu** [comment]
@dengfuping 这个在组件里面用到了clip，然后G2拿到组件去做布局时候，去要根据组件占用空间来计算布局，如果G不提供这个，其实还是要在上层去做 @hustcc

**Comment by dengfuping** [comment]
- 主要看 G2 的需求，如果这个问题会影响 G2 功能的实现，还是应该由 G 这一层去做。主要是需求场景要明确，大家可以讨论下。

**Comment by zqlu** [comment]
> * 主要看 G2 的需求，如果这个问题会影响 G2 功能的实现，还是应该由 G 这一层去做。主要是需求场景要明确，大家可以讨论下。 @dxq613 @simaQ

现在是在图例的翻页时候需要对图例组件内部做一些clip https://github.com/antvis/G2/pull/1757

**Comment by simaQ** [comment]
这个还是由 G 层支持下吧，因为后面一些交互的场景也会需要用到 clip  @dxq613 @dengfuping

**Comment by xiaoiver** [comment]
新版计算包围盒时会考虑 clipPath，取交集：
https://github.com/antvis/g/blob/next/packages/g/src/services/SceneGraphService.ts#L617
