### ISSUE TITLE
[4.0]虚拟group调用setClip报错

### ISSUE THREAD

**Issue by zqlu** [antvis/g#317]
![image](https://user-images.githubusercontent.com/1142242/70767225-5b78c800-1d9b-11ea-942f-2db6040b62a2.png)

canvas 是 undefined

**Comment by dengfuping** [comment]
- `ShapeBase` 和 `GroupBase` 现在是依赖于 canvas 的，对于虚拟 group，还没有挂载到画布时 canvas 为空。直接从当前元素获取 `ShapeBase` 和 `GroupBase` 更合理。
```js
element.getShapeBase();
element.getGroupBase();
```
