### ISSUE TITLE
[4.0] 动画的一些问题

### ISSUE THREAD

**Issue by simaQ** [antvis/g#332]
- [ ] 对 marker 的 symbol 属性做了差值计算，导致动画出了问题，因为 symbol 是函数

复现 demo: https://riddle.alibaba-inc.com/riddles/67b03e2e

衍生出来的问题：G 层是否应该只对部分图形属性做差值动画，而不是全部属性都做差值动画？

- [ ] `text` 属性为数值时，做差值动画时，是否应该按照原先数值的位数进行动画，比如如果是整数应该做取整操作，如果小数点位数为 1，变化过程中的数值应该也是一位小数点，而不是现在的效果：

复现 demo: https://riddle.alibaba-inc.com/riddles/ead62032

**Comment by dengfuping** [comment]
> 衍生出来的问题：G 层是否应该只对部分图形属性做差值动画，而不是全部属性都做差值动画？

- 应该加下判断，`Function` 类型的数据没法插值。

> text 属性为数值时，做差值动画时，是否应该按照原先数值的位数进行动画，比如如果是整数应该做取整操作，如果小数点位数为 1，变化过程中的数值应该也是一位小数点，而不是现在的效果

- 用的差值库 [d3-interpolate](d3-interpolate) 应该不支持类似的配置，我想想怎么在 G 这一层支持。

**Comment by xiaoiver** [comment]
新版动画系统兼容 Web Animation API：
https://g-next.antv.vision/zh/docs/api/animation
