### ISSUE TITLE
[4.0] 当 shape 的 bbox 出现  NaN 时，局部刷新就会绘制出错（不绘制），G 层可否处理下，比如抛个异常也妥

### ISSUE THREAD

**Issue by simaQ** [antvis/g#343]
如题，否则 BUG 真的很难定位~~~~ 太难了！

**Comment by simaQ** [comment]
最好就是能正常绘制出来

**Comment by dengfuping** [comment]
- @simaQ  出现 `NaN` 通常都是数学计算的边界情况没有考虑到，来源有很多，没有办法统一判断。可以给一下出现 `NaN` 的例子，由 G 这边来修复。

**Comment by simaQ** [comment]
有很多原因，比如一些图形的属性为 NaN，都会导致 bbox 计算为 NaN，这个上层的情况是不好穷举的，但是只要出现 NaN G 的局部刷新就不会将图形绘制... 就会很困惑，因为在一些场景下，即使 NaN 应该也可以绘制出来的，这样才能保证健壮性

**Comment by xiaoiver** [comment]
通常都是除 0 导致
