### ISSUE TITLE
为什么不采用canvas提供的原生api isPointInStroke，而是采用js自己实现是出于什么考虑

### ISSUE THREAD

**Issue by CraigZeng** [antvis/g#35]
1. 性能方面?
2. 兼容性方面?
3. 还是原生api有什么bug?

**Comment by dxq613** [comment]
标准的 canvas 的 api 下没有这个接口，当然这个方法的本质是重新绘制一遍，性能开销也比数学运算要差。

http://www.w3school.com.cn/tags/html_ref_canvas.asp

**Comment by CraigZeng** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/isPointInStroke
这个浏览器兼容性在最下面，基本都支持了

**Comment by dxq613** [comment]
isPointInPath 的性能很差，这个方法需要把图形重新绘制一遍，如果图形的量非常大的时候开销非常大。所以大多数图形的计算都是数学计算，只有 path 才使用了 isPointInPath，这个也是在包围盒筛选后才调用的，后续可以测试一下数学运算和isPointInStroke 在大量图形（1W）下的性能对比。

**Comment by CraigZeng** [comment]
@dxq613  多谢 找到了个[https://jsperf.com/ispointinpath-boundary-test-speed](https://jsperf.com/ispointinpath-boundary-test-speed)

**Comment by dxq613** [comment]
@CraigZeng 实际项目中 isPointInPath 的性能更差，这个示例中绘制和拾取一起处理了，但是在真正的项目中还有一系列层级问题，包括矩阵之类的。之前尝试过增加一个缓冲 canvas 作为拾取性能确实能够到达 O（1）但是绘制开销会加倍，特别在高交互、高动画的场景下，得不偿失。

拾取和绘制的优化没有极限，后面还会不断进行，欢迎提 MR
