### ISSUE TITLE
canvas.on('*') cannot listen the children's event of not bubbling without name

### ISSUE THREAD

**Issue by dengfuping** [antvis/g#352]
- 在 G6 的场景下，用户动态增加的图元，如果没有指定 name，则 `canvas.on('*')`  无法监听到该图元的非冒泡事件。
- 重现链接: https://codesandbox.io/s/elated-babbage-dbze9

**Comment by xiaoiver** [comment]
不应该使用这种用法监听事件，因为在事件处理器中还得根据事件名处理。
