### ISSUE TITLE
[4.0] group 的透明度动画在最新版本的 g-canvas 上没有生效

### ISSUE THREAD

**Issue by simaQ** [antvis/g#358]
复现 demo: http://riddle.alibaba-inc.com/riddles/ed4cb919

切换到 0.3.5 是 OK 的

**Comment by dengfuping** [comment]
- @simaQ 原先的实现是不太合理的，导致子元素可能会继承 group 的 `opacity` 属性。现在除了 `matrix`，group 上设置其他的 `attrs` 都不会影响子元素的渲染。

- 即当前 group 的动画属性只支持 `matrix`，其他的绘图属性都不支持。这种场景，将动画直接应用到 text 上比较合理。

**Comment by dxq613** [comment]
group 上的属性理论上说在 canvas 和 svg 版本都可以由 shape 继承，大多数属性会导致包围盒的变化，在 canvas 层次的计算太复杂了，所以没有默认支持。但是 opacity 属性不会影响包围盒，所以opacity 支持还是有必要的，可以仔细分析一下。
另外 SVG 和 Canvas 的兼容性也需要考虑一下。
