### ISSUE TITLE
局部渲染问题汇总

### ISSUE THREAD

**Issue by dengfuping** [antvis/g#372]
- [ ] 由于目前图形的包围盒并未考虑箭头，导致图形更新在局部渲染下会出现箭头的残影。
- [ ] g6 的自定义 shape 在局部渲染模式下渲染异常。
- [ ] 包围盒计算没有处理 B 路径命令，导致局部渲染不出来。

**Comment by zhixiaotong** [comment]
@dengfuping @xiaoiver 麻烦请教一下，最近在了解局部刷新，想深入了解这里面的细节，我看了语雀的文档，有了很大启发，但仍有疑问。我想了解如果连线很密集的情况，拖动节点的时候，由于清除的区域是矩形嘛，可能会包含连线的区域，那么连线会重绘。重绘的连线也需要重新擦除线的区域，这个线的区域又会跟其他节点有重合。请问这个怎么识别呢？怎么处理拖动节点的时候，重绘连线，又不卡顿。
