### ISSUE TITLE
Marker 文档缺失

### ISSUE THREAD

**Issue by TomHuangCN** [antvis/g#38]

**Comment by BigBigWen** [comment]
同求marker 文档

**Comment by OXOYO** [comment]
m

**Comment by dengfuping** [comment]
Hello @TomHuangCN. Please provide a online reproduction by forking this link https://codesandbox.io/s/g-reproduction-template-w9gb5 or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.

你好 @TomHuangCN, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://codesandbox.io/s/g-reproduction-template-w9gb5) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。

![](https://gw.alipayobjects.com/zos/antfincdn/y9kwg7DVCd/reproduce.gif)

**Comment by dengfuping** [comment]
Hello @TomHuangCN. Please provide a online reproduction by forking this link https://codesandbox.io/s/g-reproduction-template-w9gb5 or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.

你好 @TomHuangCN, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://codesandbox.io/s/g-reproduction-template-w9gb5) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。

![](https://gw.alipayobjects.com/zos/antfincdn/y9kwg7DVCd/reproduce.gif)

**Comment by cookHu** [comment]
加1

**Comment by dengfuping** [comment]
- 可以参考以下示例:

```js
import { Canvas } from "@antv/g";

const canvas = new Canvas({
  containerId: "root",
  width: 400,
  height: 400
});

const group = canvas.addGroup();
const circle = group.addShape("marker", {
  attrs: {
    x: 50,
    y: 100,
    r: 10,
    lineWidth: 2,
    stroke: "blue",
    fill: "red"
    symbol: "circle" // square, diamond, triangle, triangle-down,
  }
});

canvas.draw();
```

- 完整示例可以参考: https://codesandbox.io/s/g-marker-demo-ezsuh

**Comment by dengfuping** [comment]
- G 4.0 会提供官网，包含使用教程、API 文档、Demo，可以关注这个 #172.

**Comment by cookHu** [comment]
@dengfuping 能给出具体4.0发布时间吗？

**Comment by dengfuping** [comment]
@cookHu 已经有 beta 版发布了，4.0 不同的渲染模式拆成了不同的包
- Canvas 版: [@antv/g-canvas](https://www.npmjs.com/package/@antv/g-canvas)
- SVG 版: [@antv/g-svg](https://www.npmjs.com/package/@antv/g-svg)

- 4.0 的官网和完整文档要等 11.22 才能放出了。

**Comment by dengfuping** [comment]
- Marker 文档可见 https://g.antv.vision/zh/docs/api/shape/marker
