### ISSUE TITLE
g-svg 问题汇总

### ISSUE THREAD

**Issue by simaQ** [antvis/G#388]
- [x] group 设置 clip 后进行动画，动画结束后将 clipShape 移除，group 上的图形也被移除了，复现 riddle: http://riddle.alibaba-inc.com/riddles/ebaecdaa

```ts
clipShape.animate({
  height: 160
}, {
  duration: 1000,
  easing: 'easeQuadOut',
  callback: () => {
    // 移除 clipShape
    group.set('clipShape', null);
    clipShape.remove(true); // 动画结束需要将剪切图形销毁
  }
});
```

**Comment by simaQ** [comment]
- [ ] group matrix 动画不执行

复现 demos : http://riddle.alibaba-inc.com/riddles/cf9bea7

**Comment by simaQ** [comment]
- [ ] opacity 不生效

http://riddle.alibaba-inc.com/riddles/8b40fef3

**Comment by simaQ** [comment]
- [ ] fill: null，先被填充成黑色

复现 DEMO： http://riddle.alibaba-inc.com/riddles/722198f9

![image](https://user-images.githubusercontent.com/6628666/74311856-5a6c1300-4dab-11ea-88a0-40e67ca0a1f4.png)

**Comment by dengfuping** [comment]
> * [ ]  group 设置 clip 后进行动画，动画结束后将 clipShape 移除，group 上的图形也被移除了，复现 riddle: http://riddle.alibaba-inc.com/riddles/ebaecdaa
> 
> ```ts
> clipShape.animate({
>   height: 160
> }, {
>   duration: 1000,
>   easing: 'easeQuadOut',
>   callback: () => {
>     // 移除 clipShape
>     group.set('clipShape', null);
>     clipShape.remove(true); // 动画结束需要将剪切图形销毁
>   }
> });
> ```

- `clip` 相关的还是通过 `setClip` 和 `getClip` 两个接口方法去操作，不推荐直接设置 `clipShape` 的方式。通过 `setClip(null)` 是生效的，不过 `clipShape.remove(true)` 的处理逻辑有问题，已 #394 中修复。

**Comment by hustcc** [comment]
- [ ] 所有 shape 不和 Shape、Group、Canvas 同级导出吗？https://github.com/antvis/g/blob/master/packages/g-canvas/src/index.ts#L1

**Comment by dengfuping** [comment]
- [ ] SVG 元素事件 mouseenter 等事件不响应: [https://riddle.alibaba-inc.com/riddles/75a38a00](https://riddle.alibaba-inc.com/riddles/75a38a00)
- [ ] SVG 调用 `canvas.draw()`，会重复绘制而没有清空之前的内容。
- [ ] `canvas.set('autoDraw', false)` 不生效。
