### ISSUE TITLE
@antv/g@3.0.0-beta.2    babel: command not found

### ISSUE THREAD

**Issue by demohi** [antvis/g#39]
### Summary
> @antv/g@3.0.0-beta.2 build-lib /Users/xxx/node_modules/_@antv_g@3.0.0-beta.2@@antv/g
> babel src --out-dir lib

sh: babel: command not found

**Comment by nuintun** [comment]
Same problem

**Comment by leungwensen** [comment]
new version is published, please update to solve this. so sorry for the problem.
