### ISSUE TITLE
Text 文本支持纵向绘制

### ISSUE THREAD

**Issue by dengfuping** [antvis/g#400]

**Comment by xiaoiver** [comment]
在 `g-canvaskit` 中已支持沿路径绘制文本：
https://g-next.antv.vision/zh/docs/api/renderer/canvaskit#%E6%B2%BF%E8%B7%AF%E5%BE%84%E7%BB%98%E5%88%B6%E6%96%87%E6%9C%AC

<img width="414" alt="截屏2022-06-20 下午1 50 25" src="https://user-images.githubusercontent.com/3608471/174533755-b43d122a-34b7-4d8f-92f6-d694c1e1f823.png">
