### ISSUE TITLE
局部刷新导致文本出现尾巴

### ISSUE THREAD

**Issue by simaQ** [antvis/g#416]
![2020-02-22 10-56-21 2020-02-22 10_58_08](https://user-images.githubusercontent.com/6628666/75085249-3bffd780-5562-11ea-934d-f1a740ef0fff.gif)
![Snip20200222_45](https://user-images.githubusercontent.com/6628666/75085251-402bf500-5562-11ea-8896-5a4577afef5d.png)

**Comment by xiaoiver** [comment]
#812 
#990

新版对于 `g-canvas` 脏矩形渲染下的包围盒计算给予了更大的“宽容度”，虽然还做不到根据 `lineJoin` 和 `miter` 精确计算。
