### ISSUE TITLE
【IE11 兼容性】在ie11下，各个图表的 text 均无法展示

### ISSUE THREAD

**Issue by linhuiw** [antvis/g#429]
### 问题描述：IE11 下 text 无法展示。

![image](https://user-images.githubusercontent.com/722603/75336268-caa78800-58c5-11ea-8b50-ee9bdd452db5.png)

**Comment by BlackGanglion** [comment]
@antv/g@3.5.0-beta.3 下在 jsbin.com 上测试了一下，确实无法显示 text，shape circle 没有问题

https://jsbin.com/fezuzelive/edit?html,output

**Comment by BlackGanglion** [comment]
g版本： @antv/g-canvas@0.3.26

浏览器：IE11

操作系统：win10

完全没有绘制结果

https://jsbin.com/komihaz/edit?html,output

**Comment by hustcc** [comment]
@dengfuping 同时看一下 4.x 是否也会存在和这个问题吧。

**Comment by dengfuping** [comment]
> @dengfuping 同时看一下 4.x 是否也会存在和这个问题吧。

- 也有的这样的兼容性问题，会一起修掉。

**Comment by dengfuping** [comment]
- `@antv/g@3.5.0-beta.1` 版本在 IE 11 下可以正常展示，但 `@antv/g@3.5.0-beta.2` 和 `@antv/g@3.5.0-beta.3` 两个版本不行。问题是在 #271 这个 PR 中引入，IE 浏览器无法自动处理 `maxWidth` 参数为空的情况。已在 [@antv/g@3.5.0-beta.4](https://www.npmjs.com/package/@antv/g/v/3.5.0-beta.4) 版本修复。

**Comment by dengfuping** [comment]
- @linhuiw @BlackGanglion 可以更新下依赖进行验证。

**Comment by BlackGanglion** [comment]
> * @linhuiw @BlackGanglion 可以更新下依赖进行验证。

我这边验证没有问题了，非常感谢
