### ISSUE TITLE
源码问题：g-base Animation 对象中 _paused 字段从未被置为 true

### ISSUE THREAD

**Issue by entronad** [antvis/g#451]
- [x] I have searched the [issues](https://github.com/antvis/g/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/antvis/g/blob/0e1fcb57c85ca1e1bc4d516b12791f05364af71b/packages/g-base/src/abstract/element.ts#L557](https://github.com/antvis/g/blob/0e1fcb57c85ca1e1bc4d516b12791f05364af71b/packages/g-base/src/abstract/element.ts#L557)

### Steps to reproduce
从代码逻辑看，Timeline 对象中的 update 方法是通过 Animation 对象的 _paused 字段判断是否已暂停的，但全局搜索整个 g 代码仓库，发现从未有将 _pause 置为 ture 的逻辑过，仅有在 Element.resumeAnimate() 方法中有置为 false的逻辑。是否在Element.pauseAnimate()漏掉了将 _paused 置为false的逻辑？

### What is expected?
在Element.pauseAnimate()包含 _paused 置为false的逻辑

### What is actually happening?
整个 g 代码仓库没有置 _paused 为 true 的逻辑

| Environment | Info |
|---|---|
| g | 3.4.7 |
| System | windows |
| Browser | chrome |

**Comment by dengfuping** [comment]
- 实际在 [Element.ts](https://github.com/antvis/g/blob/master/packages/g-base/src/abstract/element.ts#L567-L571) 中的 `pauseAnimation()` 函数中，通过 `set()` 接口设置了 `_paused` 的值:
https://github.com/antvis/g/blob/bb7fdece660d7fae9778a6a695bf81043a8716a5/packages/g-base/src/abstract/element.ts#L567-L571

**Comment by entronad** [comment]
@dengfuping 

谢谢回复。这段代码指出的是 cfg._pause.isPaused ，但是我想说的是 animation._isPaused

原先在 element.pauseAnimate()中，仅通过 this.set('_pause', ...) 将 cfg._pase.isPaused 设置为 true ，但并未将 animation._paused 设置为 true 。
animation._paused 是一个优化更新性能的判断标记，仅在以下一处使用： https://github.com/antvis/g/blob/0e1fcb57c85ca1e1bc4d516b12791f05364af71b/packages/g-base/src/animate/timeline.ts#L91 
因此就算从未被设置为 true 也不会影响逻辑和测试，但就起不到优化的作用。

我提了个 PR: https://github.com/antvis/g/pull/464 请看一下。

**Comment by dengfuping** [comment]
- @entronad 👍，代码阅读得很仔细，已在 [PR](https://github.com/antvis/g/pull/464) 下回复 [CR 意见](https://github.com/antvis/g/pull/464/files#r405279402)。
