### ISSUE TITLE
SVG 自定义箭头的坐标系与 Canvas 不一致

### ISSUE THREAD

**Issue by Yanyan-Wang** [antvis/g#455]
- [ ] I have searched the [issues](https://github.com/antvis/g/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/988c6775](https://riddle.alibaba-inc.com/riddles/988c6775)

### Steps to reproduce
SVG 自定义箭头的坐标系与 Canvas 不一致。

### What is expected?
SVG 自定义箭头的坐标系与 Canvas 一致

### What is actually happening?
SVG 自定义箭头的坐标系与 Canvas 不一致。

| Environment | Info |
|---|---|
| g | 3.4.7 |
| System | Mac |
| Browser | Chrome |

**Comment by xiaoiver** [comment]
新版中坐标系与具体渲染器无关：
https://g-next.antv.vision/zh/docs/api/canvas#%E5%9D%90%E6%A0%87%E7%B3%BB
