### ISSUE TITLE
Canvas 高度 500px 情况下，父容器是 505px

### ISSUE THREAD

**Issue by simaQ** [antvis/g#459]
详见 issue: 

* https://github.com/antvis/G2/issues/2159
* https://github.com/antvis/G2/issues/2264

导致的问题：

![2020-04-03 10-11-12 2020-04-03 10_11_33](https://user-images.githubusercontent.com/6628666/78317813-e32a5280-7595-11ea-9171-de8e466a1c14.gif)

是否考虑在 G 这一层加上样式解决下?

**Comment by xiaoiver** [comment]
目前给 `<canvas>` 加样式的逻辑如下，只会设置 `width / height`：
https://github.com/antvis/g/blob/0fc4d2a017fafa8df2eb3f9b65e262e59f1c2f56/packages/g/src/utils/dom.ts#L5-L10
