### ISSUE TITLE
dom shape 的事件

### ISSUE THREAD

**Issue by Yanyan-Wang** [antvis/G#479]
- [ ] I have searched the [issues](https://github.com/antvis/g/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/5f646ef3](https://riddle.alibaba-inc.com/riddles/5f646ef3)

### Steps to reproduce
dom Shape 不支持拾取以及各类内置事件

### What is expected?
dom Shape 支持拾取以及各类内置事件

### What is actually happening?
dom Shape 不支持拾取以及各类内置事件

| Environment | Info |
|---|---|
| g | 3.4.7 |
| System | Mac |
| Browser | Chrome |

**Comment by MartinsYong** [comment]
<https://github.com/antvis/g/blob/master/packages/g-svg/src/canvas.ts#L33>
以及
<https://github.com/antvis/g/blob/master/packages/g-svg/src/canvas.ts#L35>

`!SHAPE_TO_TAGS[parent.tagName]` 应改为 `!Object.values(SHAPE_TO_TAGS).includes(parent.tagName)`
