### ISSUE TITLE
带 A 的 path 在某些情况下不能拾取

### ISSUE THREAD

**Issue by Yanyan-Wang** [antvis/g#492]
- [ ] I have searched the [issues](https://github.com/antvis/g/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/8a5f0a2e](https://riddle.alibaba-inc.com/riddles/8a5f0a2e)

### Steps to reproduce
在 demo 链接中可以看到下弦的弧可以被拾取到，上弦的弧拾取不到

### What is expected?
带 A 的 path 在任何情况下可以拾取到

### What is actually happening?
带 A 的 path 在某些情况下不能拾取

| Environment | Info |
|---|---|
| g | 3.4.7 |
| System | Mac |
| Browser | Chrome |

**Comment by YYL1999** [comment]
这个链接应该是阿里内网访问的吧   对于想看看的人 打不开  还劳烦下次放个codesandbox

**Comment by xiaoiver** [comment]
新版重构了下 `@antv/util` 中 path 部分。现在对于路径定义首先会进行 normalize，这一步会将相对命令转成绝对命令，然后转成三次贝塞尔曲线，即仅包含 `M | C | Z` 命令，用于后续拾取。因此解决了这个问题。
