### ISSUE TITLE
平移画布到视野外后平移回来不显示

### ISSUE THREAD

**Issue by Yanyan-Wang** [antvis/g#494]
- [ ] I have searched the [issues](https://github.com/antvis/g/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/ef9f6b47](https://riddle.alibaba-inc.com/riddles/ef9f6b47)

### Steps to reproduce
在 demo 链接中，先将方框拖拽到画布外（拖拽方框实际上在拖拽最外层 group）；然后点击画布空白处，让最外层 group 平移 （200，0）。
预期结果：方框回到视野当中。实际结果：方框未出现。
经排查与 localRefresh 有关，如果将 localRefresh 关掉则是正常的

### What is expected?
平移画布到视野外后平移回来正常显示

### What is actually happening?
平移画布到视野外后平移回来不显示

| Environment | Info |
|---|---|
| g | 3.4.7 |
| System | Mac |
| Browser | Chrome |

**Comment by dengfuping** [comment]
- Closed via #550.
