### ISSUE TITLE
将G2中的marker沉到G

### ISSUE THREAD

**Issue by paleface001** [antvis/g#495]
目前G的marker类型太少了，使用components自定义legend的时候不大方便，可以把定义在G2层的marker沉下来。

**Comment by Me-Momo** [comment]
🙆同意. 沉淀之后 之前marker point依赖G2marker的部分也可以通知我改一下

**Comment by paleface001** [comment]
好滴，我找时间提个MR~

**Comment by paleface001** [comment]
> 🙆同意. 沉淀之后 之前marker point依赖G2marker的部分也可以通知我改一下

好滴，我找时间提个MR~

**Comment by hustcc** [comment]
G 提供外部注册 marker 方式吗？让 G 增加 包大小，扩展 G2 的 marker 也不太好。

最好我感觉是作为 G 的周边，一个周边的 Marker 包。

**Comment by Me-Momo** [comment]
我记得之前有registerMarker的方式
周边的轻量小型包 也挺适合（话说之前是不是有G-Component

**Comment by paleface001** [comment]
> G 提供外部注册 marker 方式吗？让 G 增加 包大小，扩展 G2 的 marker 也不太好。
> 
> 最好我感觉是作为 G 的周边，一个周边的 Marker 包。

看看会增加多少吧，这个包大小不在G增加，也得在G2Plot增加，做混合图表的时候自定义图例需要

**Comment by hustcc** [comment]
3.6.x 依赖的 G 是有 registerMarker 方法，G2 3.6.x 中的 marker 就是注册进去的。

> 我记得之前有registerMarker的方式
> 周边的轻量小型包 也挺适合（话说之前是不是有G-Component

**Comment by xiaoiver** [comment]
Marker 本质只是定义不同的 Path 而已，不应内置。
