### ISSUE TITLE
Warning '"export 'transform' was not found in '@antv/matrix-util'' after update to @antv/g-canvas@0.4.11

### ISSUE THREAD

**Issue by UlfR** [antvis/g#515]
After update to @antv/g-canvas@0.4.11 i`ve received such warnings in console:
✔ Webpack  Compiled successfully in 5.90s
 WARNING  Compiled with 5 warnings                                                                                                                                                     warning  in ./node_modules/@antv/g-canvas/node_modules/@antv/g-base/esm/abstract/element.js
"export 'transform' was not found in '@antv/matrix-util'
 warning  in ./node_modules/@antv/g-canvas/node_modules/@antv/g-base/esm/abstract/element.js
"export 'transform' was not found in '@antv/matrix-util'
 warning  in ./node_modules/@antv/g-canvas/node_modules/@antv/g-base/esm/abstract/element.js
"export 'transform' was not found in '@antv/matrix-util'
 warning  in ./node_modules/@antv/g-canvas/node_modules/@antv/g-base/esm/abstract/element.js
"export 'transform' was not found in '@antv/matrix-util'
 warning  in ./node_modules/@antv/g-canvas/node_modules/@antv/g-base/esm/abstract/element.js
"export 'transform' was not found in '@antv/matrix-util'

Package versions:
@antv/g-canvas: "0.4.11"
@antv/g-base: "0.4.6"
@antv/matrix-util: "3.0.3"

**Comment by dengfuping** [comment]
- @UlfR  更新下依赖试试，`@antv/g-canvas: "0.4.12"` 应该修复了这个问题。

**Comment by UlfR** [comment]
> * @UlfR  更新下依赖试试，`@antv/g-canvas: "0.4.12"` 应该修复了这个问题。
Seems to be fixed. No warnings after update.
