### ISSUE TITLE
模式填充得到黑色

### ISSUE THREAD

**Issue by JunYang-tes** [antvis/g#530]
- [ ] I have searched the [issues](https://github.com/antvis/g/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/infallible-elbakyan-p3g32?file=/src/index.js)

### Steps to reproduce
无

### What is expected?
以antv的logo填充

### What is actually happening?
以黑色填充

| Environment | Info |
|---|---|
| g | 3.4.9 |
| System | mac |
| Browser | chrome |

---
估计是图片异步加载后没有重新绘制

![image](https://user-images.githubusercontent.com/17270099/82201532-1d2b9a00-9933-11ea-8f52-3db8257482e9.png)

**Comment by xiaoiver** [comment]
#977 #878 
确实在图片加载完成后需要进行一次重绘。

在 `g-webgl` 中看的比较明显，因为默认纹理使用了黑色，所以能看到一闪而过：
![Uploading May-25-2022 15-27-38.gif…]()
