### ISSUE TITLE
支持canvas的arc原生api，例如startAngle和endAngle参数

### ISSUE THREAD

**Issue by xinlei3166** [antvis/g#532]
- [ ] I have searched the [issues](https://github.com/antvis/g/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
利用arc可以绘制一个动态loading或者半圆型饼图。

### What does the proposed API look like?
```
    group.addShape('arc', {
      name: 'arc',
      attrs: {
        x: 250,
        y: 250,
        r: 100,
        startAngle: '0',
        endAngle: '1*Math.PI',
        fill: '#fff',
        stroke: 'l(0) 0:#1890ff 0.5:#7ec2f3 1:#fff',
        lineWidth: 20
      },
    })
```

**Comment by xiaoiver** [comment]
暂时没支持 Arc 或者扇形这样的图形
