### ISSUE TITLE
pixelRatio 的逻辑问题，且没有处理页面缩放

### ISSUE THREAD

**Issue by hustcc** [antvis/g#544]
https://github.com/antvis/g/blob/2a70a95c90f25915f1b443d76447ff9cd61bab20/packages/g-canvas/src/canvas.ts#L54-L57

导致 pixelRatio 不正确，很多用户反馈图形模糊，但是在 svg 上就是 ok 的。检索到这里，大概是上述代码的问题。

不知道取整的考虑是什么？

**Comment by dengfuping** [comment]
- 已经改为向上取整了，这个问题应该已经修复。取整的原因就是为了解决浏览器缩放导致 `pixelRatio` 出现浮点数的问题:
https://github.com/antvis/g/blob/7aabda94935a344bac26eb7da97cd25925990fcb/packages/g-canvas/src/canvas.ts#L54-L57

**Comment by hustcc** [comment]
@dengfuping 发布版本了吗？

**Comment by sjchao** [comment]
> * 已经改为 `ceil` 向上取整了，这个问题应该已经修复。取整的原因就是为了解决浏览器缩放导致 `pixelRatio` 出现浮点数的问题:
>   https://github.com/antvis/g/blob/7aabda94935a344bac26eb7da97cd25925990fcb/packages/g-canvas/src/canvas.ts#L54-L57

`pixelRatio`是浮点数会有什么问题吗？我看F2那边并没有取整
https://github.com/antvis/F2/blob/d761b84d099c69a6a27ced338b35360b9c921688/src/graphic/engine/canvas.js#L90
