### ISSUE TITLE
svg mouseenter 等事件不响应

### ISSUE THREAD

**Issue by Yanyan-Wang** [antvis/g#546]
- [ ] I have searched the [issues](https://github.com/antvis/g/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/8ec529e2](https://riddle.alibaba-inc.com/riddles/8ec529e2)

### Steps to reproduce
链接中可见鼠标进入 path 不打印 entering

### What is expected?
svg 图形响应 mouseenter 等事件

### What is actually happening?
svg 图形不响应 mouseenter 等事件

| Environment | Info |
|---|---|
| g | 3.4.10 |
| System | Mac |
| Browser | Chrome |

**Comment by HbuJiaTian** [comment]
发现同样的问题，求解答。

**Comment by xiaoiver** [comment]
新版对于事件进行统一处理，因此不同渲染器下应当表现一致。
