### ISSUE TITLE
支持小程序

### ISSUE THREAD

**Issue by kreja** [antvis/g#556]
- [x] I have searched the [issues](https://github.com/antvis/g/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
有一个组件直接依赖了 g，现在这个组件需要支持小程序。
@antv/g@3.5.0-beta.5 最新版依赖的 @antv/util 应该是 1.3.1，这个版本里有 document，所以 @antv/g@3.5.0-beta.5 就无法在小程序里使用了，@antv/util 2.0.9 已经没有  document 了，可否升级一下？

![image](https://user-images.githubusercontent.com/7478555/84233949-eb6ab500-ab25-11ea-9965-ec5ef72516d0.png)
![image](https://user-images.githubusercontent.com/7478555/84233957-ef96d280-ab25-11ea-9607-caa73c273f64.png)

### What does the proposed API look like?
打包结果可直接用于小程序

**Comment by dengfuping** [comment]
- Closed by #561.
