### ISSUE TITLE
Shape配置项是否能尽量保持一致

### ISSUE THREAD

**Issue by Amanda111** [antvis/g#57]
### Actual behavior
使用G6的时候发现，矩形的radius仅支持一个数值，不支持数组。
```js
group.addShape('rect',{
    attrs:{
        ...
        radius: 3,  // Array is not allowed
    }
})
```

### Expected behavior
是否能与[G绘图接口Shape API](https://antv.alipay.com/zh-cn/f2/3.x/api/g.html#_Rect-%E7%9F%A9%E5%BD%A2)保持一致；包括参数值支持的类型以及参数名。
```js
new G.Shape.Rect({
  attrs: {
    x: 50, // 矩形左上角 x 坐标
    y: 50, // 矩形左上角 y 坐标
    height: 20, // 矩形高度
    width: 80, // 矩形宽度
    lineWidth: 1, // html5 canvas 绘图属性
    fill: '#1890FF', // html5 canvas 绘图属性
    strokeStyle: '#000' // html5 canvas 绘图属性
    radius: 0 // 圆角的设置，可以是数值或者数组格式，支持为四个夹角分别设置，用法同 padding
  }
})
```

**Comment by elaine1234** [comment]
在`3.1.0-beta.8`中已支持数组形式`[r1, r2, r3, r4]`， 分别对应左上、右上、右下、左下角的半径。
- radius缩写为 1或 [ 1 ] 相当于 [ 1, 1, 1, 1 ]
- radius 缩写为 [ 1, 2 ] 相当于 [ 1, 2, 1, 2 ]
- radius 缩写为 [ 1, 2, 3 ] 相当于 [ 1, 2, 3, 2 ]
