### ISSUE TITLE
redraw 会造成 svg 动画下会造成不必要的重绘

### ISSUE THREAD

**Issue by BlackGanglion** [antvis/g#61]
https://github.com/antvis/g/commit/05acf75f81e50c3938f7d9d3b37071a4fe6e9517#diff-6f0de38008ec4b414692f0933cda543eR117

这个 commit 变更后 svg 在动画下会造成不必要的重绘，例如下图中的 `<g />` 标签

![aug-14-2018 00-14-17](https://user-images.githubusercontent.com/9314735/44044212-75f5b44a-9f57-11e8-9055-a321f0056a98.gif)

```javascript
import g from '@antv/g';

const Canvas = g.Canvas;

var canvas = new Canvas({
  containerId: 'main',
  renderer: 'svg',
  width: 500,
  height: 600
});

var group = canvas.addGroup();
var shape = group.addShape('circle', {
  attrs: {
    x: 100,
    y: 100,
    r: 50,
    fill: 'red'
  }
});

canvas.draw();

shape.animate({
  x: 50,
  y: 50,
}, 5000, 'easeLinear', () => { }, 1000);
```

**Comment by elaine1234** [comment]
此issue在`3.1.0-beta.11`中已修复，感谢反馈
