### ISSUE TITLE
clearChanged 参数存在 undefined 情况

### ISSUE THREAD

**Issue by baizn** [antvis/g#638]
- [ ] I have searched the [issues](https://github.com/antvis/g/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/antvis/G6/issues/2216](https://github.com/antvis/G6/issues/2216)

### Steps to reproduce
访问上面链接，将要收起的元素拖到左上角，点击节点，控制台报错。

| Environment | Info |
|---|---|
| g | 0.5.1 |
| System | mac |
| Browser | chorme最新 |

---
树图收起时如果收起后所有元素都在视窗范围外时，会出现clearChanged 方法参数 elements 存在 undefined 的情况。

**Comment by lxitgto** [comment]
I has the same issue.
