### ISSUE TITLE
vite support

### ISSUE THREAD

**Issue by nilptr** [antvis/g#657]
- [x] I have searched the [issues](https://github.com/antvis/g/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/nilptr/vite-antv-demo](https://github.com/nilptr/vite-antv-demo)

### Steps to reproduce
1. run `npm run dev`
2. vist http://localhost:3000/

| Environment | Info |
|---|---|
| g | 0.5.1 |
| System | - |
| Browser | - |

---
error： g2plot.js:10160 Uncaught ReferenceError: require is not defined

located at https://github.com/antvis/g/blob/94a8dc424d66ce717fcd62af359ee60293317712/packages/g-base/src/index.ts -> `const pkg = require('../package.json');`

g-canvas & g-svg have the same issue.

reference: https://github.com/antvis/G2Plot/issues/1894

**Comment by nilptr** [comment]
https://github.com/antvis/g/pull/658#issuecomment-731552575 @hustcc 帅哥看下怎么解决呗

**Comment by hyrious** [comment]
Same problem. I think we should use rollup or esbuild to build the esm result instead of tsc. Rollup is used by vite and helps you using correct esm syntax so that you can find and fix these errors.

**Comment by hustcc** [comment]
已经解决，并发版本，同时也修改上层的 G2，G2Plot~
