### ISSUE TITLE
代码引入package.json文件，导致打包后版本泄露问题

### ISSUE THREAD

**Issue by dangyyeo** [antvis/g#673]
g-svg、g-base、g-canvas都存在这个问题

![image](https://user-images.githubusercontent.com/12290338/101350285-b1f2e680-38c9-11eb-8ed0-e39fa870412e.png)
![image](https://user-images.githubusercontent.com/12290338/101350587-2af23e00-38ca-11eb-8765-3ed172d63a6e.png)

**Comment by hustcc** [comment]
已处理。
