### ISSUE TITLE
局部刷新机制优化大数据问题请教

### ISSUE THREAD

**Issue by ltsok** [antvis/G#684]
看了你们的局部刷新机制如下：
1.首先确定图形的矩形包围盒
2.清除这个包围盒内的颜色，设置这个区域为 clip 区域
3.重新绘制所有跟这个区域相交的图形
若图上连线或其他元素横跨了整个屏幕，此时该矩形包围盒是取的整个屏幕大小吗，若是则图上的所有元素是否会重新绘制一遍，如何在该种情况下裁剪出需要更新的脏区。

**Comment by zhixiaotong** [comment]
同问，求教。我想了解如果连线很密集的情况，拖动节点的时候，由于清除的区域是矩形嘛，可能会包含连线的区域，那么连线会重绘。重绘的连线也需要重新擦除线的区域，这个线的区域又会跟其他节点有重合。请问这个怎么识别？

**Comment by zhixiaotong** [comment]
我看了上万数据的那个demo，一点不卡顿，真的很赞。但是不清楚连线的区域怎么识别和擦除不影响其他节点。

**Comment by xiaoiver** [comment]
@ltsok 基本原理正如您所说，只是我们在为了提升 “查询区域内有哪些图形” 的效率，使用了 RBush 这样的空间索引：
https://github.com/antvis/G/blob/next/packages/g-plugin-canvas-renderer/src/CanvasRendererPlugin.ts#L495

**Comment by xiaoiver** [comment]
> 同问，求教。我想了解如果连线很密集的情况，拖动节点的时候，由于清除的区域是矩形嘛，可能会包含连线的区域，那么连线会重绘。重绘的连线也需要重新擦除线的区域，这个线的区域又会跟其他节点有重合。请问这个怎么识别？

无论是线还是节点，发生拖动都意味着包围盒需要更新，所有“脏”的包围盒会合并成一个擦除。

**Comment by ltsok** [comment]
学习了，感谢

**Comment by zhixiaotong** [comment]
> > 同问，求教。我想了解如果连线很密集的情况，拖动节点的时候，由于清除的区域是矩形嘛，可能会包含连线的区域，那么连线会重绘。重绘的连线也需要重新擦除线的区域，这个线的区域又会跟其他节点有重合。请问这个怎么识别？
> 
> 无论是线还是节点，发生拖动都意味着包围盒需要更新，所有“脏”的包围盒会合并成一个擦除。

谢谢回复。我是对连线的绘制有困惑，因为线条太多，且连线的类型可能是各种曲线，所以当局部绘制的时候，连线对象是全量绘制吗？
