### ISSUE TITLE
addShape的设计在做 react 版本（reconciler）的设计时，发现无法将createInstance和appendXXX分开

### ISSUE THREAD

**Issue by dandanba** [antvis/g#693]
addShape的设计在做 react 版本（reconciler）的设计时，发现无法将createInstance和appendXXX分开；
建议将 new Shape({}) 和 canvas.add() 分开

**Comment by xiaoiver** [comment]
https://github.com/pmndrs/react-three-fiber

**Comment by zengyue** [comment]
> addShape的设计在做 react 版本（reconciler）的设计时，发现无法将createInstance和appendXXX分开；
> 建议将 new Shape({}) 和 canvas.add() 分开

现在就是分开的呀，你要做react版本是不是要结合react使用，我的理解只要封装一个jsx-runtime就可以了吧 https://zh-hans.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html

**Comment by zhanba** [comment]
已添加react render，欢迎尝试使用
