### ISSUE TITLE
2021年 g-webgl 有什么规划吗

### ISSUE THREAD

**Issue by zuiidea** [antvis/g#701]

**Comment by vellengs** [comment]
看上去 webgl  版本流产了。

**Comment by hustcc** [comment]
可以看看 dev-inversify 分支的。

**Comment by vellengs** [comment]
@hustcc 大致什么时间节点会有个release 版本出来？

**Comment by xiaoiver** [comment]
目前支持了 WebGL 渲染器：
https://g-next.antv.vision/zh/docs/api/renderer/webgl
