### ISSUE TITLE
AbstractCanvas模块下的setDOMSize中的context.scale调用错误

### ISSUE THREAD

**Issue by chuxiaorong** [antvis/g#722]
- [ ] I have searched the [issues](https://github.com/antvis/g/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/g-reproduction-template-w9gb5?file=/src/index.js)

### Steps to reproduce
在mac的高分屏下，某些时候窗口大小变化后，会报 r.scale is not a function
经过查看源码，发现 context.scale 调用错误
<img width="621" alt="D15F28D6-5C9D-4500-9A0A-6875E4010BCD" src="https://user-images.githubusercontent.com/24957354/107017764-8a8d9c80-67da-11eb-8220-3a2ed36d4177.png">
context 上的 scale 是一个 number，原生方法在其原型链上
打印结果如下：
<img width="408" alt="3F7F8031-8D90-4491-8C47-0A3A39409057" src="https://user-images.githubusercontent.com/24957354/107017841-a5f8a780-67da-11eb-9583-b068291fb702.png">

| Environment | Info |
|---|---|
| g | 0.5.5 |
| System | mac big sur |
| Browser | chrome v88 |

**Comment by xiaoiver** [comment]
暂时没能复现这个问题。查了下 scale 方法的支持度应该非常高才对：
https://developer.mozilla.org/zh-CN/docs/Web/API/CanvasRenderingContext2D/scale
