### ISSUE TITLE
使用 gatsby 构建官网报错

### ISSUE THREAD

**Issue by xiaoiver** [antvis/g#741]
使用 `gatsby-theme-antv` 构建官网站点时遇到了两个问题：

1. 构建时，报错 `Can't resolve 'module' in @babel/standalone`
2. 运行时，报错 `languageDefinitions is undefined`，来自 `monaco-editor`

查看了下安装的依赖：
```json
"@babel/standalone": "7.13.6",
"monaco-editor": "0.22.2",
```

第一个问题来自 `@babel/standalone` 的最新版本中使用了 `require('module')` 而 `7.12.6` 中没有

## 暂时的解决方案

使用 `yarn` 的 `resolution` 锁定以下依赖的版本：
```json
"resolutions": {
    "@babel/standalone": "7.12.6",
    "monaco-editor": "0.21.2"
  }
```

**Comment by hustcc** [comment]
直接来一个 Pr 吧(o^^o)
