### ISSUE TITLE
@antv/g-canvas 0.5.9提示不可用的版本，是怎么回事，现在本地更新包更新不了了，麻烦大佬看下

### ISSUE THREAD

**Issue by jingleding** [antvis/g#774]
@antv/g-canvas 0.5.9提示不可用的版本，是怎么回事，现在本地更新包更新不了了

**Comment by xiaoiver** [comment]
可以安装 0.5.10 试下

**Comment by zhanba** [comment]
latest 更新为0.5.10版本，重新安装下试试

**Comment by jingleding** [comment]
0.5.10 这个版本看npm上没有

**Comment by zhanba** [comment]
> 0.5.10 这个版本看npm上没有

有的啊 https://www.npmjs.com/package/@antv/g-canvas
