### ISSUE TITLE
need effective element.clone()

### ISSUE THREAD

**Issue by TomHuangCN** [antvis/g#78]
need effective element.clone()

So far, there are many problems to clone element in [this way](https://github.com/antvis/g2/blob/master/src/geom/mixin/active.js#L106).  Such as :

1. clone lots of unneed attr such as `strokeStyle`.
2. shallow copy means matrix is the same object between origin shape and copy shape , it will cause other problems.

**Comment by elaine1234** [comment]
- `const clonedShape = shape.clone()`
只深拷贝所有绘图相关属性，不包含`id`等配置属性，不包含父子关系等。需要绘制拷贝的图形时，需要将`clonedShape`添加到某个group中，调用`canvas.draw()`
- `const cloneGroup = group.clone()`
只拷贝所有子图形(所有子shape，子group)的绘图属性，不包含配置信息和父子关系。需要绘制拷贝的组时，需要将`clonedGroup`添加到某个group中，调用`canvas.draw()`
