### ISSUE TITLE
【G 5.0】绘制 smooth path 的时候，需要手动 unshift ['M', 0, 0] 才能绘制正常

### ISSUE THREAD

**Issue by visiky** [antvis/g#795]
![image](https://user-images.githubusercontent.com/15646325/126483524-afddb30b-0c00-4058-9d51-05222b908e39.png)

**Comment by xiaoiver** [comment]
问题原因是 `g-canvas/svg` 在绘制 Path 时遇到 C 命令未考虑偏移量

**Comment by xiaoiver** [comment]
![image](https://user-images.githubusercontent.com/3608471/128302894-a31fb092-9def-49fb-9d17-35a55fa4fc98.png)
