### ISSUE TITLE
需要自定义箭头的功能

### ISSUE THREAD

**Issue by TomHuangCN** [antvis/g#8]

**Comment by dxq613** [comment]
### 目前 arrow 功能分解成了两个配置项：

* startArrow 
* endArrow 

两项只能设置 true、false

### 如果两个配置项都需要自定义，目前存在几个问题：

* 配置项如何设计的易用、易理解
* 箭头需要考虑当前箭头的角度、偏移量，起始、结束箭头各有不同

### 可以考虑的方案

* 方案一：内置几个箭头，startArrow,endArrow 可以直接指定字符串如： startArrow: 'solid' endArrow: 'square' 之类
* 方案二：startArray 和 endArrow 都可以是回调函数，用户自己绘制

这两个方案各有利弊：
* 方案一
  + 优点：不需要进行角度的计算，不需要自己进行绘制
  + 缺点：限定的箭头类型，箭头的大小都是内置的规则
* 方案二：
  + 优点：灵活
  + 缺点：自定义成本高，需要考虑角度、偏移量、线的粗细各种情况


@simaQ @TomHuangCN  各自说一下自己的意见

**Comment by dxq613** [comment]
之前的拾取没有考虑箭头，如果考虑更加复杂。

**Comment by simaQ** [comment]
除了 startArrow，endArrow，目前箭头我还支持角度和长度设置的，arrowLength  arrowAngle

**Comment by simaQ** [comment]
两个方案应该都提供

**Comment by dxq613** [comment]
接口不好设计：

```js
startArrow: {
 type: 'arrow',
 callback: function(ctx, point, length, angle) {

 },
 leghth: 10,
 angle: 'auto' // Math.PI（角度还是弧度）
}

```

**Comment by dxq613** [comment]
还是提供注册箭头的方法

```
G.registerArrow('start', 'new-arrow' ,function(cfx, point, legth, angle) {

});

```

**Comment by TomHuangCN** [comment]
目前来看，方案一，成本太高，缺乏设计。应优先提供方案二：

1. 箭头的部分的拾取，目前位置没有用户感知过这个问题，我认为没必要考虑
1. 注册机制太重了，建议还是回调机制。

```js
startArrow: obj || callback
```

**Comment by TomHuangCN** [comment]
另外，是否应该和设计同学，同步一下默认的箭头样式的设计？

![image](https://user-images.githubusercontent.com/6113694/34599389-012ff120-f22d-11e7-9c54-5665cfcca17d.png)

**Comment by elaine1234** [comment]
Duplicate of #32
