### ISSUE TITLE
官网 demo 链接 404

### ISSUE THREAD

**Issue by 2912401452** [antvis/g#810]
[https://antv-g-next.gitee.io/zh/docs/guide/diving-deeper/scenegraph](url)

404 链接 [https://antv-g-next.gitee.io/zh/examples/scenegraph/group#webgl-solarsystem](url)
![20B00600-A5AE-461E-A717-56CD5BF0279F](https://user-images.githubusercontent.com/42212176/143216415-5f7b9720-b6b9-4ece-a004-356de270e7ee.png)

**Comment by xiaoiver** [comment]
感谢～马上修复
