### ISSUE TITLE
g5.0 比 g4.0 在对大数据量画布做平移操作时性能下降很多

### ISSUE THREAD

**Issue by geekrainy** [antvis/g#816]
- [ ] I have searched the [issues](https://github.com/antvis/g/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
实际测试画布渲染 1000 节点放到同一个分组，对分组进行平移操作，帧率远不及 g4.0 下的表现。相机是无法满足只移动某一分组，即某一层下的元素的功能需求的。因此还是有场景需要对元素进行平移等操作的，这些场景下 5.0 的性能无法满足要求。

### What does the proposed API look like?
期望 g5.0 版本能带来 g4.0 下同样的性能表现。

**Comment by xiaoiver** [comment]
感谢提醒～
我觉得问题出在多次 fill 没有合并的问题上：
![Uploading 截屏2021-11-26 下午4.30.59.png…]()

**Comment by xiaoiver** [comment]
另外我发现 g 4.0 在旋转时也有很大问题，应该只有 15 FPS 左右：
https://codesandbox.io/s/frosty-mclean-xiqz1?file=/index.js

**Comment by xiaoiver** [comment]
升级到最新版即可：
```json
"@antv/g": "^5.0.1",
"@antv/g-canvas": "^1.0.1",
```

目前采用的优化手段是批量更新 R-tree 中的节点。

另外上面 batch 的手段的确能大幅减少 draw call，特别适合批量渲染“同类”图形（我们在 g-webgl 中就使用了该方法），把多个样式相同的图形合并成一个 path，这样只需要设置一次样式，一次性 fill/stroke：
https://stackoverflow.com/questions/23668459/issue-on-drawing-multiple-circles-on-html5-canvas

但有一个很大的限制，由于合并成了一个 path 绘制，就无法体现各个图形间的 z-index 了
http://jsfiddle.net/4jtov6uq/

**Comment by geekrainy** [comment]
<img width="679" alt="WX20211203-141339@2x" src="https://user-images.githubusercontent.com/7333266/144554630-1511ddb7-a483-4b33-8fa4-77a799eb0ff7.png">

更新后报错了

**Comment by xiaoiver** [comment]
> <img alt="WX20211203-141339@2x" width="679" src="https://user-images.githubusercontent.com/7333266/144554630-1511ddb7-a483-4b33-8fa4-77a799eb0ff7.png">
> 
> 更新后报错了

这个 bug 修复了，可以更新下试试。

**Comment by xiaoiver** [comment]
之前的渲染排序需要修改，没有必要使用 materialize path：
<img width="323" alt="截屏2022-02-28 上午11 08 26" src="https://user-images.githubusercontent.com/3608471/155917667-ac4f992f-8908-4e00-bb7d-e0260ac2953f.png">
