### ISSUE TITLE
window11 yarn 报错

### ISSUE THREAD

**Issue by ue007** [antvis/g#849]
执行yarn之后，报错信息如下：
`MSBUILD : error MSB3428: δ�ܼ��� Visual C++ �����VCBuild.exe����Ҫ��������⣬1) ��װ .NET Framework 2.0 SDK
��2) ��װ Microsoft Visual Studio 2005���� 3) ������������װ��������λ�ã��뽫��λ�����ӵ�ϵͳ·���С� [D:\UE007\canvas\g\node_modules\sharp\build\binding.sln]
MSBUILD : error MSB3428: δ�ܼ��� Visual C++ �����VCBuild.exe����Ҫ��������⣬1) ��װ .NET Framework 2.0 SDK
��2) ��װ Microsoft Visual Studio 2005���� 3) ������������װ��������λ�ã��뽫��λ�����ӵ�ϵͳ·���С� [D:\UE007\canvas\g\node_modules\sharp\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\UE007\canvas\g\node_modules\libnpm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)        
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\UE007\\canvas\\g\\node_modules\\libnpm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"`

**Comment by xiaoiver** [comment]
建议查看下 windows 环境下 yarn 的安装问题
https://classic.yarnpkg.com/lang/en/docs/install/#windows-stable

**Comment by ue007** [comment]
thx
