### ISSUE TITLE
mouseover will fire loop when use svg renderer

### ISSUE THREAD

**Issue by TomHuangCN** [antvis/g#87]
### Steps to reproduce the behavior

https://codepen.io/DoriTong/pen/gBWQaG

**Comment by dengfuping** [comment]
- 由于 `mouseover` 事件会冒泡，子元素不断销毁重建，mouseover 也会不断触发，并不断冒泡至 canvas 层。如果不想不断触发的话，应该监听 `mouseenter` 事件。
