### ISSUE TITLE
g-svg包 Path类中未实现getStartTangent和getEndTangent方法

### ISSUE THREAD

**Issue by huangchen1031** [antvis/g#872]
- [ ] I have searched the [issues](https://github.com/antvis/g/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gracious-grass-knjt3)

### Steps to reproduce
只用svg渲染时，labelCfg中设置position为'start' 或者 'end'时直接js报错

| Environment | Info |
|---|---|
| g | 0.5.6 |
| System | - |
| Browser | - |

**Comment by xiaoiver** [comment]
切线这样的集合信息应当与渲染器（`g-svg/canvas/webgl`）无关，在新版中我们在 `@antv/g` 的 Polyline、Path 中提供该 API：
https://g-next.antv.vision/zh/docs/api/basic/polyline#getstarttangent-number
