### ISSUE TITLE
VUE可以使用antv/g吗

### ISSUE THREAD

**Issue by a871545252** [antvis/g#899]
- [ ] I have searched the [issues](https://github.com/antvis/g/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
VUE可以使用antv/g吗

### What does the proposed API look like?
VUE可以使用antv/g吗

**Comment by zhanba** [comment]
可以，有两种方式：
- 简单的方式是通过ref， https://vuejs.org/guide/essentials/template-refs.html#template-refs， 拿到canvas元素，然后使用g的API绘图。
- 高级的方式是，实现vue自定义render，参考 https://vuejs.org/api/custom-renderer.html，可以声明式的使用g。
