### ISSUE TITLE
No matching bindings found for serviceIdentifier: Symbol(ContextService)

### ISSUE THREAD

**Issue by pureJim** [antvis/g#905]
## 新版本重新安装后无法使用，必须降低版本才能使用。

> 使用到 `@antv/g` 和 `@antv/g-canvas`

<img width="829" alt="截屏2022-03-14 01 24 13" src="https://user-images.githubusercontent.com/93514455/158071530-1d98898f-98ab-4bb6-8431-66e27add5a15.png">

**Comment by xiaoiver** [comment]
我在 Codesandbox 上看是好的：
https://codesandbox.io/s/yi-npm-module-xing-shi-shi-yong-g-wjfux?file=/index.js

版本是：
```js
"@antv/g": "5.0.15",
    "@antv/g-canvas": "1.0.14",
    "@antv/g-plugin-3d": "1.0.16",
    "@antv/g-plugin-control": "1.0.13",
    "@antv/g-svg": "1.0.12",
    "@antv/g-webgl": "1.0.18",
```

**Comment by pureJim** [comment]
又好了，周五一直到今天下午都不可以的，一直报错，降了版本之后很多api都不能使用，显示畸形。                                                   下午我用umi搭建了一个新项目，只安装了`"@antv/g": "5.0.15"`,`"@antv/g-canvas": "1.0.14"`,这两个库会直接报错无法执行，提示需要安装 `Reflect metadata` :(😔
