### ISSUE TITLE
在图上加上阴影，但阴影却加在了border上

### ISSUE THREAD

**Issue by d9767192** [antvis/g#91]
### Summary
如题，我想在g6当中实践画一个长方形，然后加上border跟阴影，但加上去后发现阴影是加到了border上而非长方形上; 正确的behavior是将阴影加到长方形上才对，具体可参考这个测试例：

[https://riddle.alibaba-inc.com/riddles/eb5f81df](https://riddle.alibaba-inc.com/riddles/eb5f81df)

错误的结果图：

预期的结果：（用纯canvas去画的情况）

![Uploading image.png…]()

[https://codepen.io/d9767192/pen/EdoXEp](https://codepen.io/d9767192/pen/EdoXEp)

与有田讨论觉得可以区分 fillShadow 和 strokeShadow

再麻烦青湳老师帮忙看看

**Comment by elaine1234** [comment]
建议使用两个shape来画，第一个画fill和shadow，第二个画shadow。参考：https://riddle.alibaba-inc.com/riddles/d8df1d1c
