### ISSUE TITLE
[g-webgl] 渲染bug

### ISSUE THREAD

**Issue by CraneXHu** [antvis/g#932]
使用webgl渲染器，出现bug，浏览器是chrome只支持webgl1.0，错误如下（应该是不支持WEBGL_draw_buffers扩展的情况没处理好）
 Uncaught TypeError: Cannot read properties of null (reading 'drawBuffersWEBGL')

**Comment by xiaoiver** [comment]
确实我们目前使用了 MRT，因此在 WebGL1 下依赖 WEBGL_draw_buffers 扩展。

**Comment by xiaoiver** [comment]
不过我想问下，您使用的操作系统和 Chrome 版本是什么？
我在自己的 mac safari 14.x（也仅支持 WebGL1） 下测试，它是支持 WEBGL_draw_buffers 扩展的。

**Comment by CraneXHu** [comment]
1. 操作系统Windows 7，Chrome版本99.0.4844.84，我这边不支持WEBGL_draw_buffers 扩展。
2. 详细错误信息如下图 
![image](https://user-images.githubusercontent.com/11334906/160274152-d7f1f70d-38bb-4c1f-91be-1eec01bad49b.png)

**Comment by xiaoiver** [comment]
了解，之前我没有做该扩展不支持的考虑。
目前我用该扩展的场景只有 MRT 拾取，我会尽快拆成两个 render pass。

**Comment by xiaoiver** [comment]
更新到 5.0.19 版本解决。
