### ISSUE TITLE
@antv/g-webgpu@0.5.5 版本源码在哪呀，遇到点问题可以提个pr吗

### ISSUE THREAD

**Issue by 2012shenghua** [antvis/G#934]
@antv/g-webgp

**Comment by xiaoiver** [comment]
可以提在这里，原来的仓库已经存档了。

可以问一下您使用 `@antv/g-webgpu` 是在做 GPGPU 嘛？
如果是的话，我们现在提供的是基于 WebGPU 的方案，相比原来 WebGL 的能力要强很多。

感兴趣可以查看：
https://g-next.antv.vision/zh/docs/guide/diving-deeper/gpgpu
