### ISSUE TITLE
与antv/l7同时使用会冲突

### ISSUE THREAD

**Issue by Vermouth-vi** [antvis/G#939]
与antv/l7一起使用，会报错 Cannot apply @injectable decorator multiple times.

**Comment by xiaoiver** [comment]
从报错信息上看是我们使用的 mana-syringe 和 inversify 有冲突。
我去写个例子复现下。

**Comment by Liu-wenxiang** [comment]
> 从报错信息上看是我们使用的 mana-syringe 和 inversify 有冲突。 我去写个例子复现下。

您好，还没有解决吗
