### ISSUE TITLE
[g] 在 document 上提供 elementsFromPoint 方法

### ISSUE THREAD

**Issue by xiaoiver** [antvis/g#948]
将拾取方法挂载到 document 对象上：

返回该位置最顶层的**一个**图形：https://developer.mozilla.org/zh-CN/docs/Web/API/Document/elementFromPoint
返回该位置最顶层的**一组**图形：https://developer.mozilla.org/zh-CN/docs/Web/API/Document/elementsFromPoint

```js
const topMostElement = document.elementFromPoint(30, 20); // circle1
const elements = document.elementsFromPoint(30, 20); // [circle1, circle2]
```

如果点在可视范围外，返回 null 和空数组。

**Comment by zhanba** [comment]
这个API应用场景是什么，第一次听说。。

**Comment by xiaoiver** [comment]
> 这个API应用场景是什么，第一次听说。。

目前有两个场景：
* G2 的新版交互语法需要使用，并不一定由鼠标、触摸屏这类交互事件触发
* 在 WebWorker 中配合 OffscreenCanvas 渲染时，如果要实现拾取也需要

只需要把 G 内部实现的拾取方法暴露出来就行，唯一的问题可能是 `g-webgl` 使用的是 GPU 拾取，因此只能返回最顶层的一个对象。`g-canvas` 使用数学方法 + [isPointInPath](https://developer.mozilla.org/zh-CN/docs/Web/API/CanvasRenderingContext2D/isPointInPath)  `g-svg` 直接使用的 elementFromPoint。

**Comment by xiaoiver** [comment]
目前 `g-webgl` 在 elementsFromPoint 方法上性能有问题。批量更新 `interactive` 导致

**Comment by xiaoiver** [comment]
来自：https://www.khronos.org/events/webgl-meetup-april-2022
在拾取时可以利用相机偏移，仅渲染鼠标（拾取点）周围一小块区域，而非整个屏幕，可以显著提升性能。
