### ISSUE TITLE
`parsePath` 解析 path 字符串支持不完整

### ISSUE THREAD

**Issue by alphatr** [antvis/g#95]
RT，[`parsePath`](https://github.com/antvis/g/blob/1af56fd0b197ec8ad3819c1b27ffb7ccadfe416f/src/util/format.js#L39) 解析  `M259.3 17.8L194 150.2 47.9 171.5c-26.2 3.8-36.7 36.1-17.7 54.6l105.7 103-25 145.5c-4.5 26.3 23.2 46 46.4 33.7L288 439.6l130.7 68.7c23.2 12.2 50.9-7.4 46.4-33.7l-25-145.5 105.7-103c19-18.5 8.5-50.8-17.7-54.6L382 150.2 316.7 17.8c-11.7-23.6-45.6-23.9-57.4 0z` 这样一个 SVG path 字符串，和 SVG 本身绘制结果不一样；

在这段字符串中，解析会有两个问题：

1. L 的连写：`L194 150.2 47.9 171.5` 应该解析为 `["L", 194, 150.2],["L", 47.9, 171.5]`, 而不是 `["L", 194, 150.2, 47.9, 171.5]`

2. 没有空格间隔的负数：`l-25-145.5 105.7-103` 应该解析为 `["l", -25, -145.5], ["l", 105.7, -103]` 而不是 `["l", "-25-145.5", "105.7-103"]`

这段字符串在 svg 中支持 [demo](https://jsbin.com/xepafuyaju/edit?html,output)

**Comment by elaine1234** [comment]
感谢指出。目前G不支持path的省略写法，建议使用M x,y L x2,y2的标准写法。也欢迎你优化我们的parse逻辑，给我们提pr😊
