### ISSUE TITLE
[g] 使用轻量级的 tapable 替代

### ISSUE THREAD

**Issue by xiaoiver** [antvis/g#970]
tapable 对于浏览器环境支持度并不好，例如在 vite 中直接使用会报错，需要在构建工具中进行配置：
https://github.com/antvis/g/issues/947

另外它体积也不小，我们需要一个轻量化的流程管理替代实现。
https://github.com/funnyecho/hamon

Codesandbox UMD:
https://codesandbox.io/s/yi-umd-xing-shi-shi-yong-g-701x5?file=/index.js
Codesandbox NPM:
https://codesandbox.io/s/yi-npm-module-xing-shi-shi-yong-g-wjfux?file=/index.js

**Comment by hustcc** [comment]
使用 [hamon](https://github.com/funnyecho/hamon) 替换之后可以节省多少大小？另外这个包靠谱吗？

**Comment by xiaoiver** [comment]
tapable 在 hook 执行多次的场景下性能提升很明显。

下图为使用 tapable 替代实现的执行效果，场景为 2w 个旋转的 Circle，可以看出 `render` 这个 hook 连续执行 2w 次，虽然每次耗时不高，但累积起来就会导致帧率明显下降（50 fps -> 12 fps）：
<img width="400" alt="截屏2022-05-09 上午11 34 46" src="https://user-images.githubusercontent.com/3608471/167365564-739bd3cf-6efc-43b9-b1bb-0d4cbe8804c7.png">

而使用 tapable 后，几乎看不到这种累积的耗时：
<img width="355" alt="截屏2022-05-09 下午4 12 33" src="https://user-images.githubusercontent.com/3608471/167368179-bd410b0a-9bc3-41f2-883e-4498f0085eaf.png">

如果不考虑大量连续调用的场景，确实没必要使用 tapable。但正如 webpack 作者在这个 issue 中所写，采用 `new Function` 静态编译后在这样的场景下的确能带来非常明显的提升效果：
ISSUE：https://github.com/webpack/tapable/issues/162

另一个担忧是 tapable 是否只适合在 Node 端运行，而不适合浏览器端。个人认为还是得根据场景而定，如果需要流程管理而恰好又存在大量连续调用的场景，那 tapable 确实很合适。

之前 tapable 确实有使用箭头函数导致无法在 ie11 中运行的问题，但作者修复了该问题：
https://github.com/webpack/tapable/pull/151/files
