### ISSUE TITLE
Vite + Vue3 +TypeScript 下 创建CanvasRenderer 失败啊。    

### ISSUE THREAD

**Issue by moon989** [antvis/g#997]
<script setup lang="ts" >

import { ref, onMounted } from 'vue';
import { Circle, Canvas } from '@antv/g';
import { Renderer as CanvasRenderer } from '@antv/g-canvas';

const container = ref<HTMLDivElement>();
onMounted(() => {
    let canvas_Container = container.value!
    let renderer = new CanvasRenderer();
    // let canvas = new Canvas({
    //     renderer,
    //     container: 'container',
    //     width: 800,
    //     height: 800,
    // });
});

</script>

<template>
  <div>
    <div class="container" ref="container" />
  </div>
</template>

**Comment by moon989** [comment]
基本的代码，无法执行啊。
`
<template>
  <div id="container"></div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import TodoItem from '../components/TodoItem.vue'
import { todoStore, remove } from '../store/todoStore'
import { Circle, Canvas } from '@antv/g';
import { Renderer as CanvasRenderer } from '@antv/g-canvas';

export default defineComponent({
  components: { TodoItem },
  setup () {
    return { todoStore, remove }
  },
  mounted() {
    // create a canvas
    const canvas = new Canvas({
      container: 'container',
      width: 500,
      height: 500,
      renderer: new CanvasRenderer(), // select a renderer
    });

    // create a circle
    const circle = new Circle({
      style: {
        cx: 100,
        cy: 100,
        r: 50,
        fill: 'red',
        stroke: 'blue',
        lineWidth: 5,
      },
    });

    // append to canvas
    canvas.appendChild(circle);

    // add listener for `click` event
    circle.addEventListener('click', function () {
      circle.style.fill = 'green';
    });
  }

})
</script>

`

**Comment by moon989** [comment]
### 官方网站的例子，简单的代码都无法执行 。是不是不支持 Vue3？ 。 对 tsconfig 有什么特殊要求？

<template>
 <div id="container"></div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import TodoItem from '../components/TodoItem.vue'
import { todoStore, remove } from '../store/todoStore'
import { Circle, Canvas } from '@antv/g';
import { Renderer as CanvasRenderer } from '@antv/g-canvas';

export default defineComponent({
  components: { TodoItem },
  setup () {
    return { todoStore, remove }
  },
  mounted() {
    // create a canvas
    const canvas = new Canvas({
      container: 'container',
      width: 500,
      height: 500,
      renderer: new CanvasRenderer(), // select a renderer
    });

    // create a circle
    const circle = new Circle({
      style: {
        cx: 100,
        cy: 100,
        r: 50,
        fill: 'red',
        stroke: 'blue',
        lineWidth: 5,
      },
    });

    // append to canvas
    canvas.appendChild(circle);

    // add listener for `click` event
    circle.addEventListener('click', function () {
      circle.style.fill = 'green';
    });
  }

})
</script>

**Comment by moon989** [comment]
看来，还是得退回到 0.5版本用啊。

**Comment by xiaoiver** [comment]
稍后给你一个 vite 的例子。

**Comment by xiaoiver** [comment]
> 看来，还是得退回到 0.5版本用啊。

老版本不再维护了，推荐使用新版。
文档：https://g-next.antv.vision/zh/docs/guide/introduce
vite 例子：https://stackblitz.com/edit/vitejs-vite-nnas74?file=src/main.ts
